### ISSUE TITLE
Reduce input via the console when running `generate_report()`

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#11]
If possible, convert some of the questions and user inputs that are shown in the console to function arguments to simplify the report creation.

**Comment by z3tt** [comment]
As it could be the case that new types are featured in a report, the best workflow here is likely:

1. provide defaults for the four common types (tee, green, rough, fairway)
2. ask if those default values should be used
2.1. if yes: no further input is needed (if only common types are listed in the database)
2.2. if no: ask for the values (same as now)
3. If an uncommon type is listed, ask for the value (which is then added to the default or user-specified values in 2.)

Because of the non-common types and the fact that not all of the common types need to be featured in the database/report, passing those as function input is the less preferred approach. With the suggested workflow, we still have to answer a question in the console but it is only 1 compared to 2-5 (values for each type plus verification).

**Comment by z3tt** [comment]
The workflow has been adjusted so that less inputs are needed in case (a) no accumulation rates don't need to be calculated and/or (b) the defaults for the Grass Maximum N/month lb/1000 sq ft values.

(a) If accumulation rates should be calculated, you are asked about the specific rates and their values as before.
(b) If there is an uncommon soil type or you opt to not use the defaults, you are asked to provide the values as before.

![Screenshot 2024-06-27 at 13 43 14](https://github.com/torv72/torv-reports-v4/assets/7523556/1a86636f-e473-4963-8f81-2a2e21d046cc)

@torv72 I remember that you've mentioned two different default values for the soil types but I can't recall them. Please share them here and I'll update the defaults in the script accordingly.

**Comment by torv72** [comment]
Tee value = 0.5   Green = 0.5.   Rough = 0.7  Fairway  = 0.7

We want to make sure that a bullet point (it should be listed first) is added to the Executive Summary under it's respective header that says the following:  "All calculations are based on a monthly maximum of "X" lbs of N/M."  

X is the value that is either the default or if I enter a customized value

**Comment by z3tt** [comment]
I have adjusted the default monthly maximum values. They are also listed in the executive summary now.
