### ISSUE TITLE
Don't repeat "How to read" chart

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#14]
All trendline facets currently include a "how to read" example that shows the meaning of the different points and lines. However, those chart is repeated many times and always looks the same anyway (despite the main color used for the section). 

It might be more meaningful to

1. show this plot only once at the beginning of the report (so the reader learns how to read all the following charts) OR
2. place the plot below each trend panel but hide it (so the reader can refer to it if needed)

This also allows us to change the general workflow for these panel plots which are currently built with {patchwork} but could use a simple `facet_wrap()` in this new version (also see #13).

**Comment by z3tt** [comment]
I have implemented two different ways:

* an unfoldable summary containing the how-to-read plot (i.e. the legend is repeated multiple times)
* a link to a section called  "How to Read Trend Line Plots" below all trendline facets which features the how-to-read plot (i.e. the plot is contained only once)

I can show you the two solutions and you decide which you prefer.

**Comment by z3tt** [comment]
For the HTML version, we keep the unfoldable summary (toggle) below each set of trend line plots (already implemented).

However, it makes no sense to include those in the PDF as that format does not support interactive toggles. Here, we include the legend plot only once, either at the beginning or end of the report (or somewhere in-between?). @torv72 we just need to decide on which position will work best and I'll take care of it.

**Comment by torv72** [comment]
I'm going to sleep on this one for a few days.  Right now I'm tempted to say we put it in the Executive Summary.  If there was additional instructions about reading the report, I could see its own page.  Additional instructions could pertain to explaining the special features of the html document and how to float your "pointer" over a data point.  Just thinking out loud here.  That obviously does not pertain to pdfs though.

**Comment by z3tt** [comment]
Included in the PDF at the very end of the report as an individual section. It is referenced and linked below each trend line chart.
