### ISSUE TITLE
Use color encoding for water plots

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#15]
The dots in the water plots could be encoded with a blue sequential gradient or indicate the outcome (good/bad, positive/negative etc.).

**Comment by z3tt** [comment]
I've worked on a new version of the FAO water plot, polished and with interactivity for the HTML report. 

I have adjusted the label sizes, colors, styles, etc. I also introduced the color gradient consisting of four different colors: a general one for "low" and two colors for "medium" and "high", respectively; and an intermediate color derived from those two for the combined category "medium/high".

Two different styles, one closer to the original and one with grey rows (consistent with the MLSN plot) to make it less cluttered and easier to see the individual plots per measurement.

***Polished "original" version:***
![Screenshot 2024-10-23 at 12 29 26](https://github.com/user-attachments/assets/70b421c1-07ec-4930-a796-e81b3db371d5) 

***Gray-row version:***
![Screenshot 2024-10-23 at 12 23 30](https://github.com/user-attachments/assets/781f0704-8993-4085-aa39-e2ee1b44ad17)

*Note: The lighter colors for the bubbles are the result of the hovering; all bubbles are colored with the same intensity for the default status of the interactive plot as well as in the static plot.*

I like the grey version, as I find it easier to read and its look cleaner. I never liked all the gray lines, especially as they shift their position in between. However, with the adjusted colors and much lighter lines now I like that version too, as it is not that cluttered anymore.

**Comment by torv72** [comment]
I think they are both an upgrade to what I had before.  The gray-row version I find easier to read from the standpoint that there is no doubt what category you are in (low, medium, high) at first glance.  The polished version you do have to look for the grey lines a little bit and then you know where you are at but it still an improvement.  I really like the idea of a gradient color going from low to high.  I rarely have ever seen any values in the “high” maybe never.  Low and medium for sure all the time.   I’m fine with either and trust your judgement.
