### ISSUE TITLE
Converting geom to grob issue

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#18]
Hi Cedric.  I will send this also via your email as this is a pressing issue and I cannot generate any report until the bug is fixed.  I am working in the change-workflow branch.  I am trying to generate a report for Maroon Creek Club.  I am using the following inputs to generate the report:

 generate_report(.site_name = "Maroon Creek Club",
+                 .zip_code = 81611,
+                 .date_sample_submitted = "2024-06-06",
+                 .start_date = "2017-01-01",
+                 .warm_or_cool = "cool",
+                 .acid_extract = "Mehlich",
+                 .include_results_interpretation = FALSE,
+                 .draw_beeswarm = "Yes",
+                 .typeface = "Lato")

Below is a copy of the process and my answers:

processing file: report.Rmd
  |................                                                                                             |  15% [setup]              

processing file: templates/setup.Rmd

I found the following soil types in the database: GREEN, TEE, FAIRWAY.
I didn't find any water types in the database.
I found the following OM types in the database: GREEN.

* Does that seem correct, or do you want to exit to investigate the database before running the rest of the report? *

Type c for correct and hit ENTER to proceed, or hit any other key followed by ENTER to exit now. c

**GREENs**

I have found several dates for OM data for GREENs. Would you like to calculate the OM accumulation rate?
Type y for yes or n for no and hit ENTER. n

No problem. I'll skip that this time.

**TEEs**

I have found several dates for OM data for TEEs. Would you like to calculate the OM accumulation rate?
Type y for yes or n for no and hit ENTER. n

No problem. I'll skip that this time.

**ROUGHs**

I have found several dates for OM data for ROUGHs. Would you like to calculate the OM accumulation rate?
Type y for yes or n for no and hit ENTER. n

No problem. I'll skip that this time.

** I need some information from you in order to compile the MLSN deficit tables.
Please answer the following questions. I'll give you an opportunity to revisit your answers at the end.**

In the database, we found analyses for the following types of soil: GREEN, TEE, FAIRWAY
I will ask you in turn for the Grass Maximum N/month lb/1000 sq ft value for each of these.
        
Please type in the value (e.g. 0.85) and hit ENTER.

What is the value for soil type GREEN?   .5
What is the value for soil type TEE?   .5
What is the value for soil type FAIRWAY?   .7

Thank you.
            

* You have provided the following values. *

GREEN = 0.5, TEE = 0.5, FAIRWAY = 0.7

Are these correct? Type y for yes or n for no and hit ENTER: y

Great, I'll compile the rest of the report!

output file: setup.md

I then get the following error that I am unable to figure out.  I've not seen this one before.  I also tried the main branch and received the same error.  I'm wondering if it is a package update issue as I did update some of my packages that needed updating.

`geomtextpath::geom_textpath()`:
! Problem while converting geom to grob.
ℹ Error occurred in the 1st layer.
Caused by error in `txt$shape[, shape_vars]`:
! Can't subset columns that don't exist.
✖ Column `x_midpoint` doesn't exist.
Backtrace:
  1. ggplot2::ggsave(...)
  3. ggplot2:::grid.draw.ggplot(plot)
  5. patchwork:::print.patchwork(x)
  6. patchwork:::build_patchwork(plot, plot$layout$guides %||% "auto")
  7. base::lapply(x$plots, plot_table, guides = guides)
     ...
 30. geomtextpath::textpathGrob(...)
 31. geomtextpath:::measure_label(...)
 32. geomtextpath (local) measure(...)
 33. geomtextpath:::text_shape(...)
 35. tibble:::`[.tbl_df`(txt$shape, , shape_vars)
Called from: signal_abort(cnd, .file)
Browse[1]>

Quitting from lines 139-146 [unnamed-chunk-17] (report.Rmd)

Quitting from lines 270-286 [soil-results] (report.Rmd)

In the browser tab I get the following if this helps you.

<img width="737" alt="Screenshot 2024-06-10 at 4 25 38 PM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/386541a5-d12b-4397-afca-b87139640658">

**Comment by z3tt** [comment]
[Issue introduced in the latest version of geomtextpath](https://github.com/AllanCameron/geomtextpath/issues/118), should be solved soon in the official version on CRAN. 

Until then, please test the development version:
```
remotes::install_github("AllanCameron/geomtextpath", quiet = TRUE)
```
