### ISSUE TITLE
Being questioned on organic matter data for OM types that were not sampled

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#23]
When I run a report, in this case Maroon Creek Club, with a start date of 2024-06-06 for example, I am being asked about TEEs and ROUGH OMs even though I did not have any sampling done on these two areas.  I should only be asked if I want to calculate the OM accumulation rate if it was just sampled.  For example I have not sampled ROUGH OM in over a year but I am being asked if I want to calculate the accumulation rate.  

If this doesn't make sense, I can demonstrate it on Tuesday when we meet.

**Comment by z3tt** [comment]
Not happens anymore, closed for now.
