### ISSUE TITLE
Workflow to customize Executive Summary

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#24]
This is a workflow question.  How do I customize my comments on a report?  What is the workflow?  For example I ran an example html report for Maroon Creek Club with a start date of 2024-06-06.  The report rendered.  Part of the rendering is doing all of the calculations, etc.  The Executive Summary is automatically generated based on the calculations which I don't know until the code has run.  I add comments based on the output of the calculations.  What would be the suggested workflow?  When I run the code with a Word output, I can see the output and add my comments in the Word document, thus customizing it.  Thoughts?

**Comment by z3tt** [comment]
We made this decision before moving to the HTML version of your reports: you'll write the text inside the Rmarkdown files directly. Seems we ignored the fact that you need to see the results before being able to add the comments.

Two possible approaches here:
1. run the report as it is, look at the results in that report, and add the comments to the Rmd
2. in general, it is also possible to modify the HTML: run the report as it is, open the HTML file in an IDE (RStudio, VS Code, ...), and add your comments

As I don't know if you feel confident modifying the HTML file and as the rendering time is rather low, I'd suggest approach 1.

**Comment by torv72** [comment]
Yes.  I agree with you on adding any comments in the RMarkdown file.  When we meet maybe you can show me how to do it.  I couldn't figure out where/how to write additional comments that pertain to that specific area (Green, Tee, Fairway, etc) that is generated by the report.rmd file beginning on line 71.

I tried opening the html in Editor just to see if that worked.  At least on my computer, I get an error message saying the file is too big.  The maximum size it can be 5 MB.  The html file size was 6.1 MB.

**Comment by z3tt** [comment]
You are abolutely right, as those sections are currently created by a for loop, it is currently not possible to add custom comments to each section. let's discuss the options during the meeting today.

**Comment by z3tt** [comment]
As discussed in our meeting, the most convenient way to include your comments and modifications in both, the HTML and PDF version of the report, might be to automatically generate txt file(s) (either one for all sections or one for each section), modify those, and then source them when rendering the reports a second time.

I'll start implementing this workflow and check out if that's as promising as we hope.

**Comment by z3tt** [comment]
It's implemented and works very well.

Each time you generate a new report, a file called `exec-summary_{site-name}_{submission-date}.txt` will be generated and save to the `report` directory. Afterwards, it is sourced for the report. 

In case that file exists, it will not overwrite that file. To add custom comments, open that file, change its content, and regenerate the codes. Here is a silly example I've just tested:

![Screenshot 2024-06-27 at 11 51 33](https://github.com/torv72/torv-reports-v4/assets/7523556/f7a35a1e-c254-4010-886b-1af44ee176a1)

**Comment by torv72** [comment]
It works!!!!!!!!!!!!!!!!!!!
