### ISSUE TITLE
Printing HTML report

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#25]
I know we briefly discussed this before.  It seems that I have a mix of clients that like to print off their report that I currently provide.  However, they are very excited about the html version that we are developing with some of the interactive features but are asking if they will be able to print a high quality formatted version of the report.  In other words can we have best of "both worlds"?.  I know we can easily print the html version as it currently stands.  Can we do so and have it formatted nicely like the current version of the report from the "main" branch?

**Comment by z3tt** [comment]
A version of html and docx output generated at the same time is very unlikely to work well. However, we can test how the HTML output looks like when rendered to PDF. If the content is exactly the same, that will likely work. 

Note that we likely have to decide on some trade-offs in that case. E.g. as the bar chart on growth potential is interactive now and does not show the percentage values (which then would not be visible in the PDF...). Or, as another example, it is not possible to have toggles (i.e. collapsing some content) in a PDF format. It is not that bad, however, the toggle text (aka "header" for the toggle) will be printed as plain text in the PDF. 

I'll try to have a PDF version ready until our meeting tomorrow so we can evaluate if that is good enough and how to proceed.

**Comment by z3tt** [comment]
We can now generate both, HTML and PDF versions of the report, using the same template with dedicated settings and outputs for both output types. 

The desired output type can be passed to the new function argument `.output` in `generate_report()` which can be specified as either `"html"` or `"pdf"` or a combination to render both at the same time (specified as either `c("html", "pdf")` or `c("pdf", "html")`).
