### ISSUE TITLE
Adjust "Historical Average" Words in "How to Read this Chart

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#26]
When you click on "How to Read this Chart" in a rendered html document, the words "Historical Average" need to be adjusted so that you can read it properly. Right now it reads "Historic  ver   e".   Attached is a screenshot of what I see on my computer.

<img width="815" alt="Screenshot 2024-06-15 at 9 43 25 AM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/de7795ca-f42f-4213-8e98-430f3f9797bc">

**Comment by z3tt** [comment]
Hm, can't reproduce this behavior. Let's have a look tomorrow.

**Comment by torv72** [comment]
Looking at the html version today, I did not see the missing letters in "Historical Average". It looked normal and like it should.   I'll watch for it and see if it happens again.  If it does we can revisit.  I will close this for now.
