### ISSUE TITLE
Check page format / font sizes for PDF report

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#27]
The printable PDF report should be in letter format. As I understood the documentation for PDF files generated with Rmarkdown, this seems to be the default. Also, if I understand correctly it's mostly about the (true) font sizes when the file is printed.

@torv72 Can you check if the format looks good to you and if the font sizes (for titles and body text but also in the plots) appears to be large enough? Thanks

**Comment by torv72** [comment]
Font sizing and paper sizing appear to be good.  The only font sizing that is considerably larger and looks odd is the numbers under the "Mean measurements and recommendations".  We were discussing at one point about doing something different with this page.

**Comment by z3tt** [comment]
Yes, as discussed, this is the old content that we will modify in one of the next steps. Therefore, I didn't put much effort into polishing this section in either the PDF or the HTML file.
