### ISSUE TITLE
Visualize sand fraction results

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#28]
Currently, the sand fraction table is generated with a separate script and also relies on external inputs (i.e. it doesn't use information from the database). 

It would be good to include it in the general report workflow so it is added to both the HTML and PDF version. 
Also, I think it would be convenient if the data is sourced from the database (but don't know if that makes sense? @torv72).

I assume that the sand fraction table is not going to be included in all reports, so we'd need another Yes/No argument in the `generate_report()`function OR decide that based on the database information.

---

Notes from issue #16 on the styling of the table:
* include some in-line visualizations: add sparklines with values for first and last and/or min and max values
* apply color encoding (or other emphasis) in case a value does not meet USGA specifications

**Comment by torv72** [comment]
The data can be sourced from the MASTER DATABASE as I have been putting it in there.  

You are correct.  The sand fraction table will not always be included.  I think we can add a yes/no argument.  

If we did not want to go with a table, I did find a graphic that I wanted to show you for inspiration the other day but could not find it.  Here it is.  This is for the 0-2 cm.  We could add two more (2-4 cm) and (4-6 cm) and stack them on one page?  

![](https://www.paceturf.org/images/made/images/gallery/om2_distribution_curve_1_709_398_c1.png)

**Comment by z3tt** [comment]
That looks cool! Always better to use a chart than a table and for the HTML version the detailed measurements would be available via tooltips. for the PDF version, we might consider adding the table below the graphics. 

If I understood correctly, the data is not part of the database? What would be your preferred workflow? A manual csv table that gets sourced? Or would it be possible/make sense to add that to the database as well?

**Comment by torv72** [comment]
I agree!

Regarding my current workflow with this.  I receive the excel file from the laboratory with the results.  Then I bring that into the MASTER DATABASE.  My R skills are not good enough where I could utilize the MASTER DATABASE and utilize the data from it.  So I created a CSV file that the script I created uses.  I manually input the laboratory results each time I get them in order to create the table.  

So to answer your question.  The data is actually in the MASTER DATABASE right now.  The laboratory test type is S022.
My preferred workflow would be to only utilize the MASTER DATABASE just like we currently do.  Include a yes/no argument to include it in the report.  It would be its own separate page within the report.  I think it would also have its own "header" in the Executive Summary where I could add comments.  This would only be generated if the argument is "yes".

I like the idea of adding a table below the graphics too!

**Comment by z3tt** [comment]
Merging this with issue #16.

**Comment by z3tt** [comment]
The table is now included in both versions of the reports. The data is sourced from the MASTER DATABASE, and the recommendations are based on the examples you provided. It's now featured on a dedicated page in the PDF version after the OM results. I hope the title is fine; if I understood you correctly, it is part of the "Total Organic Matter" section and thus can use the same green color.

Please note that currently, the particle sizes in the database are not aggregated and formatted in the same way as in your isolated "fraction.csv".

![Screenshot 2024-09-03 at 11 22 11](https://github.com/user-attachments/assets/2d08719b-bad2-4fe9-8b6d-b4c967eb8107)

For instance, "Fine Gravel + Very Coarse Sand (2.0 mm + 1.0 mm)" is a single aggregated category in the "fraction.csv" file but appears as two separate entries in the database. Additionally, particle sizes in the database have a different format and style (e.g., "Fine Gravel - 2 mm (%)" in the database versus "Fine Gravel (2.0 mm)" in your example). To merge the data with the USGA recommendations effectively, we need consistent naming conventions. For now, I am adjusting the names by removing the "(%)" and wrapping the size into parentheses instead of using a hyphen, but it would be ideal to have the correct names directly in the database.

**@torv72 Please update the database with the names and particle groups you would like to use.**

I have removed the "% Retained" header line as in this version there's only a single year to show*. In general, I'd advise against making this an additional line but would suggest to add that to the overall title, i.e. as "OM 246 Sand Fractions (%Retained)". We could also consider to add the percentage sign to all values in the respective columns.

\* EDIT: We also should think about which / how many years to show. Does it make sense to display all years, assuming that at some point you have quite some long-term data? We likely run out of space in the PDF version when using more than 3-5 years anyway.

For both reports, I will include visualizations similar to the one you've shared in your previous comment, with the table displayed below the visualization (and hidden within a collapsible toggle in the HTML version).

**Comment by torv72** [comment]
Yes.  I have included the Sand Fractions as part of the Organic Matter section.  This is fine.  

"Fine Gravel + Very Coarse Sand (2.0 mm + 1.0 mm)" is a single aggregated category in the "fraction.csv" file but appears as two separate entries in the database.  You are correct.  The laboratory data that I import into the MASTERDATABASE does not have this variable.  I had to create this in the fraction.csv.  It is one of the variables for the USGA.  Can it be coded with the two added together to create that "object"?  I believe there are two others that I did that for as well. Or I could manually create in the MASTERDATABASE and do the addition myself.  

The three new "objects" would be:

![image](https://github.com/user-attachments/assets/825d3232-79e7-489c-8924-5d52525a05b6)

![image](https://github.com/user-attachments/assets/e37ad7fe-b511-4769-8580-263b05dadf58)

![image](https://github.com/user-attachments/assets/39739d7a-47a1-4276-a05c-a1b7a8cf3117)


The correct names are actually in the MASTERDATABASE.  I changed the names in the fraction.csv because I didn't know quite how to format things.

I'm fine with your suggestions for title, etc.  Whatever makes sense and looks good.

I'm fine with limiting the years to what fits just like we did in the Organic Matter table.  Do we specify a start year and end year?  Right now it doesn't make a difference at all because I don't have the data but it would give that flexibility.  Just a thought.

**Comment by z3tt** [comment]
It's absolutely possible to merge the categories in the script. It's just important that you stick to the setup we decide on. 

Option 1: Aggregated particle classes + values in the database &rarr; no post-processing necessary, you could add new particle classes (or split them again etc) whenever you want

Option 2: Raw particle classes + values in the database (as it is currently) &rarr; no additional work when adding this data to the database, but post-processing which will be picky on the particle names etc.

If you opt for option 2, how do you aggregate the values? Is it sums or averages? Or something else?

**Comment by torv72** [comment]
Go with Option 2.  The values are simply summed.  No averages or anything else.

**Comment by z3tt** [comment]
While working on this, I realized that "Fine Gravel (2.0 mm)" is featured twice in the Snowmass Club sampling: 

* Fine Gravel (2.0 mm): ≤ 3 %
* Fine Gravel + Very Coarse Sand (2.0 mm + 1.0 mm): ≤ 10 %

@torv72  How do we handle this? 

Also, is the only code used for sand fraction sampling "S022" or is there any other we need to account for?

**Comment by torv72** [comment]
S022 is the only code we need to account for. 

Fine gravel (2.0 mm) appears once by itself and then it appears again with Very Coarse Sand. They get added together. 

So it is correct.

**Comment by z3tt** [comment]
Okay, so it should be fine as it is now? Currently fine gravel is only listed together with very coarse sand (note it's only the table for now which is only included in the PDF version). Or should it be added to very coarse sand AND be listed individually (a bit more complicated to implement but possible)?

**Comment by torv72** [comment]
So attached is a table I just did for Snowmass Club last week. Each particle size should be represented in the table/graphics. Yes. You are correct. It is fine as it is now. There are three “particle sizes”where two particles are added together to create that particle size line item. Fine Gravel + very Coarse Sand is one of them. Here is a table I just did for Snowmass Club last week.

**Comment by z3tt** [comment]
Unfortunately, I cannot see any table. Here is the current version (which you'll get when generating a PDF report with `.include_sand_fraction = TRUE`). 

![Screenshot 2024-09-24 at 11 56 58](https://github.com/user-attachments/assets/a37df0d9-0c5a-456c-97a2-a4aa365a28ab)

**Comment by torv72** [comment]
I just sent a pdf copy of the sand fraction report to your Gmail account hoping it came thru. Hopefully that works.  The table you have going is almost there! You’ve got the USGA specs which is perfect. I’d  like to include the particle sizes in there that don’t have USGA specs associated with them.  They come directly from the lab report.   We can then use the USGA specs in the graphics since they offer a number to compare too. The particle sizes that don’t have a USGA  spec don’t have number to compare too. It is nice to track it though and be aware if it is going up or down.

**Comment by torv72** [comment]
Thinking out loud here….Just had a thought here and I’ll defer to your opinion and expertise.  As I think about it and look at your table with only the USGA specs associated versus all if the lab data for all of the particles like it did in my table, is it too much “clutter” and information that frankly can be gotten from the lab report itself???Do we just focus on the USGA specs which is why I’m doing this in the first place.  Was I doing too much thinking to include the other particle sizes that don’t have the specs associated with them.

**Comment by z3tt** [comment]
Argh,  I've read your latest comment too late. Saw your email with your table and started implementing it. So now it features both but we can still revert to the old workflow. 

In case you'd like to keep all particle categories but want to focus more on the USGA ones, we could also make those rows bold for example.

I also thought it'd be cool to highlight those values that do not fulfill USGA recommendations:

![Screenshot 2024-09-24 at 16 32 46](https://github.com/user-attachments/assets/f04c012c-a08f-496c-9112-bd511a83f03f)

Note: I didn't make them bold as the numbers wouldn't align nicely anymore.

**Comment by torv72** [comment]
No worries at all!The table totally works!  I like the highlighting when it does not meet USGA specs. Definitely can bold the particles that pertain to the USGA specs. Work your magic now😉

**Comment by torv72** [comment]
Just saw your note on bold and things not lining up nicely. No worries!

**Comment by z3tt** [comment]
Hi @torv72, I am working on the chart for the sand fraction result. Can you elaborate on how we calculate the statistics shown in the example from Pace Turf that you've posted on Jun 21? I try to create a similar plot but also play around with other options. Thanks!

**Comment by torv72** [comment]
Let me see what I can find. I’m driving home today as I write this.  Looking back at that chart, there are some additional particle sizes like “gravel” that I’m not measuring.  I think for our purposes I want to focus on the particle sizes that have USGA specs. In my mind, the chart would accomplish two things. It would show how the particle size compares to the USGA spec at the particular depth and then if possible show a timeline.  Does that make sense???   It would be done for each depth (0-2 cm, 2-4 cm, and 4-6 cm). I think we maximize the number on dates to whatever would fit nicely on a chart. I might have another chart I can find when I get home and I will send it off tomorrow.

**Comment by torv72** [comment]
As I drive I’ll think about it more, but it’s really just visualizing the table that you created with emphasis on the USGA specs since there is actual numbers to compare too.  The other particles are nice too track if possible but don’t want to over complicate it.

**Comment by torv72** [comment]
Here is another chart that might work better for inspiration.

![Updated OM246 sampling instructions | Asian Turfgrass Center](https://github.com/user-attachments/assets/523b23f3-296c-4059-9887-64057a22c2d3)

**Comment by torv72** [comment]
Disregard the line that is referenced as "Topdress".  The "Rootzone" line would be the values.  Also, there would not be a "Total fines" chart.  It would just be the other five.

**Comment by z3tt** [comment]
Tables are styled for the interactive report as well. I have updated the logic to display multiple sampling dates per year.

![Screenshot 2024-09-30 at 23 58 58](https://github.com/user-attachments/assets/89643fb7-841d-493d-a78e-e48617a2b873)

**Comment by torv72** [comment]
That works!

**Comment by torv72** [comment]
Just noticed something when I was generating a report for Maroon Creek Club.  I noticed that when I put "all" in for the om_season that the sand particle analysis shows both of the times that I tested the sand.  However, when I put "season" in, I only get the sand particle analysis for this fall that I did.  It does not show the spring test that I did.  

I think for the sand particle analysis, we want to show all of the tests at all times.  It is not a seasonal thing.  Any chance we can make that happen?

Here is what I get.  Notice the word "% Retained" is still a little off when only one measurement column is present.  
[TORV-report_Maroon-Creek-Club_2024-09-18 (dragged) 2.pdf](https://github.com/user-attachments/files/17252489/TORV-report_Maroon-Creek-Club_2024-09-18.dragged.2.pdf)
[TORV-report_Maroon-Creek-Club_2024-09-18 (dragged).pdf](https://github.com/user-attachments/files/17252492/TORV-report_Maroon-Creek-Club_2024-09-18.dragged.pdf)


Here is the function:

generate_report(.site_name = "Maroon Creek Club",
                .zip_code = 81611,
                .date_sample_submitted = "2024-09-18",
                .start_date = "2017-01-01",
                .om_seasons = "all",
                .om_stats = "median",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "Yes",
                .draw_beeswarm = "Yes",
                .output = c("pdf", "html"))

Again when I change the .om_season to "season" that is when I get just the one column.  

If it is easier to have Sand Fractions be its own separate report like Water and Soil  and not be a part of Organic Matter  I'm all for it.

**Comment by z3tt** [comment]
Sure, I can adjust it accordingly! For some reason assumed it's about the season as well as it's in the OM section. 

For me, it doesn't really make a difference if it gets its own section or is part of OM. My only worry is that I'd need to find another color that works with the others 😛

**Comment by torv72** [comment]
No worries at all.   The sand fractions actually come from the same samples taken for the organic matter as well. I can see how one would think that.

**Comment by z3tt** [comment]
The seasonal filtering for the sand fraction section is now ignored.

**Comment by torv72** [comment]
Good deal.

**Comment by z3tt** [comment]
I've added two different sets of charts for the sand fraction. As discussed, they show only the particles used by USGA plus sand. Both are interactive in the HTML version of the report. 

---

The first set are the horizontal bars (one facet per depth) that are meant to show an overview and emphasis (color + callout) in case the USGA specification is not met plus the difference. 
![Screenshot 2024-10-16 at 22 21 57](https://github.com/user-attachments/assets/6c747c88-1cc6-4dd4-b921-4059d2e1d5e3)
The static version includes labels to the right of the bars.

---

The other set are the connected dots (one facet per particle class) based on the visualization that you've shared a 3 weeks ago (see some previous comment). I have added a met/not met color encoding to the points. Currently, the chart does not feature the topdressing line from the example. We can add that if you like it. Not sure if we need to label the chart, I think it works as it is for an audience that know what this analysis is about.
![Screenshot 2024-10-16 at 22 22 15](https://github.com/user-attachments/assets/87b8e967-46cf-4530-a6ad-ee9c686925e9)
The static version comes with direct labels next to the dots.

---

Both charts show the same details, but actually in two very different ways. Even tough they are repetitive, that might rectify their co-existence. What do you think?

- [ ] Do you like to keep both of them? (Please tick the box if you agree.)

**Comment by z3tt** [comment]
During our meeting I've noted that the change over time is of main interest which is not shown in any of these charts*. 

- [ ] Should I create some timeline sets as well?  (Please tick the box if you agree.)

  
  
*if you look closely at the last set of charts in my previous comment, you see a tiny grey dot -- a trial to include previous data but I don't like it.

**Comment by torv72** [comment]
Yes.  I would like to have a change over time.  So go ahead create that.  

I agree. I don’t like the tiny grey dot either.  Actually I would have never seen it had you not pointed it out.

Maybe it is how it shows up on my computer, but the graphics, specifically the dots and the lines that connect them, have a “thicker” look compared to some of the graphics in the report. Maybe it is just my eye that sees that.  

I like where you are going with this it is easy to understand for me and I think we are almost there.  

In an ideal world I’d like to keep the sand fraction portion of the report no more than two pages if possible.  If not, so be it.  Whatever we need to do to make it look right.

**Comment by torv72** [comment]
Disregard by comment about the “thicker” look.  I just ran a trial report for Snowmass Club, and it doesn’t look like that at all.  Looks good.  I think it was just the screenshot that you sent.

**Comment by z3tt** [comment]
> Yes.  I would like to have a change over time.  So go ahead create that.

Which client has multiple sand fraction samplings across all three levels of depth? Could you share a suitable `generate_report()` setup with me? Or should I create a topy data set here to play around with?

> I agree. I don’t like the tiny grey dot either.  Actually I would have never seen it had you not pointed it out.

This was one of several trials--if it would make it to the final version, it would look more obvious. But that's exactly the problem, it's distracting and getting too busy. 

> Maybe it is how it shows up on my computer, but the graphics, specifically the dots and the lines that connect them, have a “thicker” look compared to some of the graphics in the report.

> Disregard by comment about the “thicker” look.  I just ran a trial report for Snowmass Club, and it doesn’t look like that at all.

You are right with both comments. The increased `stroke-width` is an interactive effect, i.e. when you hover over a geometry specific parts get highlighted and others will be less pronounced. What is highlighted and turned down can be adjusted, as well as the "thickness" of the selected geometries and the transparency of the other geometries. 

For the bar chart, bars are highlighted per particle class, i.e. across facets. For the connected dots, again the particle class is highlighted, i.e. only one facet while all others are greyed out.

> In an ideal world I’d like to keep the sand fraction portion of the report no more than two pages if possible.

This might be tight if we add the time series chart as the table alone fills one of two pages. Maybe three charts are too much anyway, let's see.

**Comment by z3tt** [comment]
> Yes.  I would like to have a change over time.  So go ahead create that.

Instead of creating another set of charts to show the time series, I thought this might be a great use case to add a sparkline visualization to the table:

![Screenshot 2024-10-18 at 15 14 49](https://github.com/user-attachments/assets/7a1eef89-f205-40a7-83c2-b8ff759e342f)

Colors indicate the sampling outcome in comparison to USGA recommendations. Nothing is drawn if a depth contains only 1 sampling date (as it is the case in this Maroon Creek example). The column is omitted in case all depths have only one sampling date).

I've also spent some time on polishing the table and added a short header text that also explains the dot colors (similar to the MLSN section; I've also colored the words as an in-text legend in that section as well). it would be cool to test it with some more samples to see the line going up and down.

**Comment by torv72** [comment]
I’m the easiest client you ever had!  

That’s so cool and it makes sense.

**Comment by torv72** [comment]
Since I’ve only done two samplings at most for any particular client this year as it is a new test that I am offering to do, I don’t have a third set to work with to see the up and down.  Only alternative I can think of is create a “dummy” third set to test it.

**Comment by z3tt** [comment]
As you like, I am sure it will work for at least up to 6-8 samplings and look even cooler with more than 2 points :) 

I think we are done with the sand fraction tables and visualizations? Or is there anything else to be added or adjusted?

**Comment by torv72** [comment]
Check out the PDF version on the sparklines.  I just ran this for Maroon Creek Club.  The lines look a little off compared to the HTML version.   If it is more of a function of the PDF format and can’t be adjusted or think I might be seeing things a little bit off, no worries.  I think that is what it is given the space constraints in which I case I’m good with it and we can close!

Here is the PDF.

￼


Here is the HTML.

￼

**Comment by z3tt** [comment]
Unfortunately, I cannot see the images. If you mean that the column is not that wide, that is correct. As we have less space available, I have reduced the figure width accordingly.  This is how the table in the PDF version looks for me:

![Screenshot 2024-10-18 at 18 07 26](https://github.com/user-attachments/assets/b4a1bd99-a5ff-4451-bf8d-fb6c6198e1e6)

Or are you refering to something else?

**Comment by torv72** [comment]
I’ll send the images to your .viz email account and see if that works

**Comment by z3tt** [comment]
Yeah, this is due to the different column widths specified for each of the report formats. I use a smaller widths in the PDF report as the space available is limited. The widths can be adjusted as you like.
