### ISSUE TITLE
Restablish web link for USGA video in pdf format if possible

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#29]
Not sure if this is possible or not.  In my current rendering from Word to pdf, I had a weblink that you could click on that would take you to a video online.  It exists in the second to last bullet point in the Organic Matter section of the Executive Summary.  I have included a screenshot.  If it is not possible, I will rewrite it as a web address instead.

I believe the words "This video" is what you click on to take you to the website for the video.

<img width="450" alt="Screenshot 2024-06-20 at 7 54 10 PM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/6c8157d1-4a99-4c80-88a3-4cf42c85b50b">

**Comment by z3tt** [comment]
Fixed.
