### ISSUE TITLE
Microsoft Word Issue

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#3]
As previously mentioned before, Microsoft Word is giving me an error when the report is rendered in the change-workflow branch.  However, when I go back to the main, everything works just fine.  Per your instructions, I opened the template docx file on the change-workflow branch.  It opened just fine.  There were no error messages at all.  

Per your instructions, I copied the template docx file from the main branch and replaced it in the change-workflow branch and ran a test report.  It seems to have solved the problem!  I'll let you close this if you would like.

**Comment by z3tt** [comment]
Perfect! I'll avoid opening the docx template on my Mac as it's likely that LibreOffice has introduced some changes that Word doesn't like.Closing this issue for now as all works fine.
