### ISSUE TITLE
Question on html viewing in iOS platform

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#30]
When opening the rendered html document on an iOS device(iPhone or iPad), I noticed that the trend line graphs and the monthly growth potential graph do not appear.  Everything else does. I was just curious if you might know why. No problem if you do not. The html renders perfect in a desktop browser.

**Comment by z3tt** [comment]
Hm, maybe the HTML version is not self-contained, i.e. when opening it on a different device (or from a different location) the links to that is missing? I need to investigate that behaviour. The rendering options are actually set to create a self-contained, stand-alone file but it seems that this does not apply to the interactive graphics created with ggiraph (as the other figures are shown, correct?).

**Comment by torv72** [comment]
What you describe is correct.  I did notice that in the "generated_reports folder where rendered reports go that there is a new folder in there that contain the exact "missing" trendliness and the growth potential chart.  I've never seen this before.  I'm wondering if this is the problem???  Or just coincidence.

**Comment by torv72** [comment]
I'm not sure if this has anything to do with this issue or not but I noticed that when I rendered a report in pdf, everything works just fine however I am getting a message that the "magick" package is required but not available.  It is not in the packages listed.  I took a screen snapshot.  

<img width="1097" alt="Screenshot 2024-06-21 at 10 32 41 AM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/6dc9d8a7-496b-4fc1-8343-f1b7f77c100e">

**Comment by z3tt** [comment]
I've just added the magick package to the project environment.

The folder TORV-report_Maroon-Creek-Club_2024-06-06_files is generated when rendering to HTML and the plots are sourced from there. Which means that (a) currently it is not self-contained and thus (b) that folder needs to be shipped with the HTML file.

I'll look into this and I am confident that we will able to make it a standalone version.

**Comment by z3tt** [comment]
Hey @torv72, I have updated the render logic and for me all content is featured in the HTML report, also when copying the file to a different directory. Can you please check if it works for you as well?

**Comment by torv72** [comment]
I got this to work by saving it as a .webarchive file instead of a .pagesource if that makes sense.  

My workflow is as follows:

1.  I generate the HTML report in R.  
2. I click on the generated report and choose "view in browser".
3. Browser opens.  HTML report appears and everything functions as designed.
4. With the HTML report open in the browser, I then choose "save as" from the file menu.  It then saves a .HTML file to my computer.  I can then email this .HTML file to my client and it will open in their browser on their desktop.  

To view the report on an IOS platform with the graphics, I got it to work by saving it as a .webarchive file.  The images are all there.  The graphics are not interactive though like they are in the .HTML file version when opened on a desktop platform.  The IOS platform does not open the .HTML version in the browser. 

I think that the PDF version that can be created will suffice if someone wants to view the report on their mobile device.   

Unless you see something different in how I am saving the generated file, I'm beginning to think this is more of an IOS problem and not one that is related to our report.

**Comment by z3tt** [comment]
@torv72 Why aren't you sending the HTML file straight from the generated-report directory? That should work or do you face any issues?

**Comment by torv72** [comment]
I confirmed that IOS and Apple did away with being able to open .HTML files for security reasons.  However, Microsoft Edge browser on the IOS platform does allow .HTML files to be opened and viewed in full.  As an experiment, I downloaded the Edge app and it works with full functionality.  I have Safari, Orion, and Chrome on my devices. 

Unless I'm doing something wrong ( I apologize if I am), I cannot or do not see how I can send a report directly from the generated_reports file.  When I click on the rendered file this is what I get as my only two options.  See below.  I then choose to open in the browser and then save it to the desktop and finally send it to the client.

<img width="734" alt="Screenshot 2024-07-08 at 8 27 55 AM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/c92c1eb5-11e7-4211-9ef4-9d6235a75988">

**Comment by z3tt** [comment]
That Mac and Apple browsers have security restrictions is nothing we can influence (I think) :|

The screenshot you've posted is from inside RStudio. While this shows the files in the directory, it does not offer the same functionality as the Finder. This file navigation is added to the Rstudio IDE to open, rename, copy, delete, ... files but not more. If you navigate to the respective folder in your Finder, you'll find the same files being placed there. Here you can access the regular Finder menu to rename, move, inspect, ... the files.

To attach it to an email,  you have to go the usual route as when attaching PDF or image files to an email: Choose "Attach files" or similar from inside your email provider. Then navigate to the generated-reports folder via the folder menu that opens up. That should work in any browser. I am on a Mac, too, and just tried to do it in Safari (which I usually don't use, but it works as well).

![Frame 1](https://github.com/torv72/torv-reports-v4/assets/7523556/72311afd-3967-4b81-bf86-0c9546520ba6)

**Comment by torv72** [comment]
Ahh...yes thank you for reminding of using the Finder.  Makes perfect sense and saves some steps.  I'll remember to do this the way you have described.

**Comment by z3tt** [comment]
Great! And all images are shipped with it and interactivity of the HTML plots is working as well? If yes, feel free to close this issue.

**Comment by torv72** [comment]
Yes everything appears to be working with the interactivity as well as all images are present.
