### ISSUE TITLE
Add a Liability Disclaimer to the end of the Executive Summary Page

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#31]
I wanted to add a professional liability disclaimer to the end of the Executive Summary page.  I think it can be done in a much smaller font size.  Here is what I came up with. 

Liability Waiver
The recommendations provided in this report are based on current industry standards and site-specific conditions. They are advisory in nature and should be implemented at the client's discretion. The consultant disclaims any liability for outcomes resulting from the application of this advice. Clients are encouraged to seek additional professional input and consider all relevant factors before proceeding with any changes. By using this report, the client acknowledges that they have read, understood, and agreed to these terms, and that they are solely responsible for any decisions made based on these recommendations.

**Comment by z3tt** [comment]
Hi Eric,

I have included two chunks, one for HTML and one for PDF, to include the liability waiver in both report versions. You'll find these versions on the html-output branch.

### HTML version
![Screenshot 2024-09-02 at 14 18 33](https://github.com/user-attachments/assets/63969240-6325-44f4-acac-3d4ca57a71e2)

### PDF version
![Screenshot 2024-09-02 at 14 37 15](https://github.com/user-attachments/assets/bc363297-d6c6-4141-b5b0-98a53f0ded87)

Let me know how you like it and in case you wish for some adjustments.

**Comment by torv72** [comment]
That works!  Thanks.

**Comment by torv72** [comment]
Quick question.  For the PDF version of the report ONLY, is it possible to move the Liability Waiver down to the bottom of a page or create more space between it and the last paragraph/bulllet point of the Executive summary?  If it creates a major headache to do this, no worries.

**Comment by z3tt** [comment]
It's now placed at the end of the page, thanks to some superb LaTeX logic 🙌 (maybe it's not as bad as I always thought... one just needs to know what to search for.)
