### ISSUE TITLE
Visualize "Mean measurements and recommendations"

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#32]
Replace the BANs with some tiny visualizations that also indicate the quality (good/neutral/bad) and how the value compares to previous measurements.

From the last sketch session, we thought about something like this:
![Screenshot 2024-09-02 at 15 00 20](https://github.com/user-attachments/assets/54d55f71-94d9-4d5a-9879-3dade73d0864)

This is a nice condensed summary, however, I find it very text-heavy and it might also create some issues as it is not straightforward to apply to all measured entities. Also, a negative change is not always bad and vice versa (this could be mitigated by using neutral colors). I personally also got confused what's the latest measurement and the comparison value.

In general, we should be careful and only add relevant information here as it should serve as a summary. All the details (correct trendlines, ranges, etc) are shown in some of the other visualizations.

So I thought of combining a draft from one of our first meetings with this approach to create a BAN together with a (more intuitive) trend indicator, the previous measurement result and the change:
![Screenshot 2024-09-02 at 14 59 59](https://github.com/user-attachments/assets/0906fddf-bf50-4a31-a960-531f9c94c473)

@torv72 How do you like that? Do you think this would work for all the outputs you'd like to show?

Edit: The colors could be fine-tuned as well to avoid good-bad indications. Also, we maybe want to add units? But that would then get rather busy and break the nice alignment... What are your thoughts on that?

(Note: Values are just made up and not consistent across the sketches.)

**Comment by torv72** [comment]
Let's go with your idea. I like your thought process behind it. I agree in that we don't need units and it will keep it clean.  I also like the idea of staying away from colors that might trigger "good" or "bad" and keep them neutral from that stand point. Great job!

**Comment by torv72** [comment]
Just thinking about this today and maybe you have too as well and I probably had mentioned it in one of our conversations.  One of the things that I don't like about the current Mean Measurement portion of the report is that it is 2 pages long because of all of the extra "white" space between each element and the one or two sentences explaining that it is the average and it is above or below the MLSN value, blah, blah. Very redundant.  

I saw in the PDF version that now the average number is represented in the Trends Over Time  graphs at the most current sampling date. 

The Measurement Results and MLSN chart shows the MLSN ppm requirement already. 

I think we are on the right track and close to eliminating the Mean Measurement portion of the report as it is written right now. 

I've really liked
what you're doing so far on everything!

**Comment by z3tt** [comment]
Thanks, Eric! I agree it’s a bit long and repeats information in a less engaging way. However, I think a quick summary of the key values in the executive summary could still be valuable. Or are you considering removing it altogether (including the 'tiny overview charts' we've planned), given that all values are already presented in the report?

**Comment by torv72** [comment]
I’m totally ok with removing it altogether as well as the tiny overview charts!  I think as you suggested if we could do a quick summary in the executive summary with the averages that would be great!  Work your magic!

**Comment by torv72** [comment]
I do for sure find value in the "Required element per area" table and the "Measurement results and MLSN values" chart.

If you see a way of improving the visualizations of these two table/charts or how they are organized within the report structure,  I'm all for it.  If they look ideal to you then I'm good.  The information is valuable though as they are specifically tailored to my MLSN calculations.

**Comment by z3tt** [comment]
> I think as you suggested if we could do a quick summary in the executive summary with the averages that would be great!

Not sure we're talking about the same things: with "tiny charts" I refer to the visual summary, cf. the tiny squares I've drafted to show the latest and previous outcome plus its change. I've planned to finalize those this week so I guess it'd be good to figure out if we need them first 🤓

I think the table is good as it is. It nicely drives emphasis on the combinations that require action and remove all other "noise". The MLSN visualizations seems to be our hate-love graphic. It is okay but I feel we could generate something more insightful / attractive. But it all comes down to what you want to show. We can adjust the level of detail, but from our several discussion about this chart I am not sure if you **want** to condense the information?

So the questions for now are:

- [ ] Are you happy with the executive summary alone?
  - [ ] If no, do you want a "tiny chart" overview of the outcomes per mineral etc that is added at the begin of the report?
- [ ] Is there any information in the "Mean measurement" section that is not mentioned elsewhere yet?
  - [ ] If no, can we remove the section overall? (no matter if you checked the tiny charts box above)
- [ ] Do you want to show the outcomes per course in the MLSN visualization?
  - [ ] Are you fine with just showing the "status" (green / orange / red)?

Please tick the answers that you agree with.

**Comment by torv72** [comment]
Yes. Quick summary in Executive Summary with the averages. Sorry for the confusion. Yes. Let’s continue on the “tiny charts”Yes. Table works. Agreed. The MLSN visualization…I’m open to improvement on that one so if you have an idea, let’s do it.

**Comment by z3tt** [comment]
For now, I have removed the section with the big numbers and the not-that-meaningful text bits. It's just excluded and easy to add again if needed.

**Comment by torv72** [comment]
Sounds good.

**Comment by z3tt** [comment]
As the final step, I am now creating the overview graphic for the executive summary. I am wondering now: For which set of data (`sample_type` + `sample_description_number_1`) are we going to show the outcomes? 

Before, the mean measurements were shown per section. Sets of tiny charts for all combinations would be too much information for the summary I fear. Should we average across the different sample descriptions?

**Comment by z3tt** [comment]
General workflow works (for now yearly averages for Soil across all sample descriptions)

![draft-tiny-charts](https://github.com/user-attachments/assets/33c7f315-86e4-4a5a-843a-cbb913aefeb3)

**Comment by z3tt** [comment]
General workflow works (for now yearly averages for Soil across all sample descriptions)

![draft-tiny-charts](https://github.com/user-attachments/assets/9ac65669-509a-4a42-a90a-951924570a63)

**Comment by z3tt** [comment]
General logic to create the tiny charts works (for now yearly averages for Soil across all sample descriptions)

![draft-tiny-charts](https://github.com/user-attachments/assets/c4e2ed0e-3fd3-475c-983d-6d5535ec97a9)

**Comment by z3tt** [comment]
General logic to create the tiny charts works (for now yearly averages for Soil across all sample descriptions)

![draft-tiny-charts](https://github.com/user-attachments/assets/8bd501dd-710d-46ab-8519-c23ef747e50b)

**Comment by torv72** [comment]
I think those would work.  Simple and too the point.  They almost could work as tufte side notes!

**Comment by z3tt** [comment]
Okay, we stick to soil results only and averaging across all outcomes? 

I assume that the same logic with default and additional measurement names applies here? (i.e. we use the same minerals and order as in the trend charts). Or do you prefer a custom list or any other logic?

Finally, I originally thought of those charts as the very first thing in the executive summary. However, as it shows soil results*, I guess it should be placed in that subsection of the exec summary? Or would you rather like them to place them in the respective sections and create one for each type, i.e. replacing the old "soil tables" with those big a** numbers?

\* we could still think about making a tiny chart with relevant across different types, but we'd need to discuss which to show and how to group them.

**Comment by torv72** [comment]
Yes.  Average across all outcomes.  If it is their first time testing, then just show a number????

Keep the same logic and order.  

I think each should be in it's own subsection in the Executive Summary.

Question….if I had a custom mineral I was tracking like set up before for special circumstances, does that show up here too?  Or does that get complicated with spacing, etc?

**Comment by z3tt** [comment]
I would adjust the logic to feature those you add via `measurements_add` in this visualization, too. That may lead to less compact and symmetric grids but that should be okay. I'll make sure the height is based on the number of rows.

> I think each should be in its own subsection in the Executive Summary.  

Does that mean you'd like to have one of those sets per type (i.e. TEE, FAIRWAY, etc)?

One other question: I removed organic matter (%) from this grid, mainly because I found the "OM" label not self-explanatory. Is this fine or would you like to keep it?

**Comment by torv72** [comment]
I’m fine with removing organic matter% and nitrogen (ppm) too if that helps.  The others I’d like to make sure to keep.

**Comment by z3tt** [comment]
We can keep nitrogen, then we have a nice full 5x2 grid. 

Once you've answered if you'd like to have one of those sets per type (i.e. TEE, FAIRWAY, etc) or one summary graphic for all (as the one I've shared for Snowmass club, still not sure it makes sense), I'll include it in the report (static only as interactive doesn't make sense here).

**Comment by torv72** [comment]
Sorry.  I’d like it to be per type (GREEN, TEE, FAIRWAY, etc)?  As it would be easier to read versus one big chart.  Unless I’m missing something.

**Comment by z3tt** [comment]
It is working now. Feel free to test it with your latest data!

We use three different colors to indicate stable (grey), decrease (orange), and increase (green). I've picked orange as it is one of the main TORV corporate color plus the dedicated color for the soil sections. I combined it with the other main corporate color, the green. To make it less colorful, I decided to pick darker variants of the corporate colors. Also, this hopefully feels less like "good" and "bad". <br><br>

![tiny_chart_APPROACH_orange_green_dark](https://github.com/user-attachments/assets/8e0845f1-9f3e-4821-809e-be1f191151dd)

<br><br>
Here is the version with the original colors (in case you like that better let me know).<br>

![tiny_chart_APPROACH_orange_green](https://github.com/user-attachments/assets/c2f0bf89-70bb-4f4c-b758-2a28afc187ad)

<br><br>
I also played around with only coloring the tiny chart and not the title but I didn't like it (again, let me know if you prefer this version).<br>

![tiny_chart_APPROACH_orange_green_lab](https://github.com/user-attachments/assets/c8fade84-2205-485d-bc3b-2c7fd94073b9)

<br><br>
I think showing just a dot for single-sample sites is cumbersome, and there is not much more to report. I decided to only show the "title lines", i.e. the abbreviation and the latest measurement results (yearly average if needed). To make the combination of abbreviations and values visual groups, I kept a small horizontal grey line to indicate grouped labels:

![tiny_chart_APPROACH](https://github.com/user-attachments/assets/cd116872-2b1d-4a88-802a-068e996904e0)

**Comment by torv72** [comment]
I like it!  In these mini charts as you already noticed, we don’t need a “good” or “bad” color.   I like your thought for color. I’ll be home late Wednesday night my time so I will pull the changes over on Thursday and test it. Looking forward to it.

**Comment by z3tt** [comment]
Perfect. I still like the encoding of the different trends (no matter if good or bad) but if you prefer it, we could also go for "all gray" or "all orange" here.

**Comment by torv72** [comment]
Nope!  We are good to go!

**Comment by z3tt** [comment]
One request here: As the featured measurements are based on your function inputs, it'd be good to provide a few more of the chemical formulas / abbreviations to match them in case you'd like to include non-default measurements.

The current list features only the default measurements:
![Screenshot 2024-10-28 at 20 41 37](https://github.com/user-attachments/assets/c314d7d5-1524-40f4-baf8-932c1048a577)

Could you prepare a short list of likely-to-be-added measurements and the respective shortcode to be used in the tiny charts? Thanks!

**Comment by torv72** [comment]
Chloride  Cl (ppm)
Boron  B (ppm)
Aluminum Al (ppm)
Soluble Salts  TSS (mmhos/cm)
Copper  Cu (ppm)
Zinc  Zn (ppm)

Let’s start with these.

**Comment by torv72** [comment]
Soluble salts may be the only one without an abbreviation that I gave the TSS abbreviation to.  Not sure if that is a problem.

**Comment by torv72** [comment]
Regarding the N2 label.  Should we put a footnote below the chart that N2 represents the Total N which is N03-N + NH4-N???

**Comment by z3tt** [comment]
I hardly can judge if that is clear to your clients or not. I simply have used the abbreviations from the MLSN chart. As there is no explanation of the labels and it was never considered problematic, I assumed it is intuitive for the audience. 

If there is a potential that they're going to misinterpret this label, we likely should add a note. I am not sure if a footnote is the best solution though, as it would be the same footnote again and again. Another solution could be a dictionary or glossary that we link to.

**Comment by z3tt** [comment]
I also decided to not include the units as it would make the overview pretty busy and even more text-heavy. If htat's a problem, we'd need to figure out another approach.

**Comment by torv72** [comment]
Agree. No units.  I’m not worried about that.

**Comment by torv72** [comment]
Let’s change the N2 to “DIN” if that is possible.  N2 is nitrogen gas even though I know what we are trying to convey.  DIN represents “dissolved inorganic nitrogen” which is what this is when combining the NO3 and NH4.  I just learned something myself!

**Comment by z3tt** [comment]
Perfect, changed it accordingly.

EDIT: My bad, I was wrong. Total nitrogen is not featured in the MLSN chart, so it looks as I've picked the wrong N2 label. Fixed now.

**Comment by torv72** [comment]
Yes. Sent from my iPhoneOn Oct 29, 2024, at 9:28 AM, Cédric Scherer ***@***.***> wrote:﻿
Perfect. Should I also adjust the label in the MLSN chart accordingly?
