### ISSUE TITLE
Update database error

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#34]
You might be working on things... not sure.  I tried pulling in some new lab data into the MASTER DATABASE.  I'm getting the following error that I've never seen before.  I confirmed that I do not have anything open.

All I am doing is executing the following:

source(here::here("aux-scripts/update-database.R"))

This is what I am getting in return.

- Project '~/Desktop/torv-reports v4' loaded. [renv 1.0.7]
- The project is out-of-sync -- use `renv::status()` for details.
> # Make sure you don't have the file open, or you'll get a "permission denied" error.
> source(here::here("aux-scripts/update-database.R"))
Error in `filter()` at torv-reports v4/aux-scripts/update-database.R:128:5:                                                       
ℹ In argument: `str_detect(file_name, file_type)`.
Caused by error in `str_detect()`:
! could not find function "str_detect"
Run `rlang::last_trace()` to see where the error occurred.

When I run rlang, this is what I get:

Backtrace:
     ▆
  1. ├─base::source(here::here("aux-scripts/update-database.R"))
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─base::suppressWarnings(suppressMessages(update_database(.test = TRUE))) at torv-reports v4/aux-scripts/update-database.R:470:1
  6. │ └─base::withCallingHandlers(...)
  7. ├─base::suppressMessages(update_database(.test = TRUE))
  8. │ └─base::withCallingHandlers(...)
  9. └─global update_database(.test = TRUE)
 10.   ├─base::nrow(filter(raw_data_list, str_detect(file_name, file_type))) at torv-reports v4/aux-scripts/update-database.R:128:5
 11.   ├─dplyr::filter(raw_data_list, str_detect(file_name, file_type)) at torv-reports v4/aux-scripts/update-database.R:128:5
 12.   └─dplyr:::filter.data.frame(raw_data_list, str_detect(file_name, file_type))
 13.     └─dplyr:::filter_rows(.data, dots, by)
 14.       └─dplyr:::filter_eval(...)
 15.         ├─base::withCallingHandlers(...)
 16.         └─mask$eval_all_filter(dots, env_filter)
 17.           └─dplyr (local) eval()

When I run rlang back_trace, I get three more lines:

└─base::.handleSimpleError(...)
 19.   └─dplyr (local) h(simpleError(msg, call))
 20.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)

**Comment by z3tt** [comment]
My apologies, I was removing the full tidyverse dependency and replaced the package collection with the individual packages. It seems I have missed that the string package is used in the script to update the database. It should work now with the latest updates.

For renv message: Make sure to update your renv project file by running `renv::status()` and, if it reports out-of-sync changes, `renv::restore()`. That should update your lock file to the current state.

**Comment by torv72** [comment]
No worries.  Your forgiven:)

**Comment by z3tt** [comment]
Does it work now? Unfortunately, I cannot test the update database routines myself.

**Comment by torv72** [comment]
I have not run the renv update yet.  FYI.

No.  Unfortunately it does not.

Here is the error I am getting now.

 Project '~/Desktop/torv-reports v4' loaded. [renv 1.0.7]
- The project is out-of-sync -- use `renv::status()` for details.
> # Make sure you don't have the file open, or you'll get a "permission denied" error.
> source(here::here("aux-scripts/update-database.R"))
Error in add_column(., !!!cols[!names(cols) %in% names(.)]) :                                                     
  could not find function "add_column"

**Comment by z3tt** [comment]
Oh my, they are adding a large number of packages here for very simple use cases. Might be worth getting rid of some dependencies but for now, I have added that library. Please try again after pulling the latest changes.

**Comment by torv72** [comment]
Whatever you did it worked!

**Comment by torv72** [comment]
My rent::status() check came back with “the project is in a consistent state"
