### ISSUE TITLE
Organic matter from MEAN to MEDIAN Question

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#36]
Quick question.  Right now  everything in the organic matter (OM) is done as "mean" calculations.  If I wanted to instead go to "median" calculations for everything regarding organic matter, would that be a major issue or as simple as replacing "mean" with "median" in the code?

**Comment by z3tt** [comment]
That should be easy to adjust. Would you like to change that for all reports or be able to switch between both options?

**Comment by torv72** [comment]
If it is easy enough to do to be able to switch between both options for all reports that would be great.  But only if it easy:).  This would also have to include the TORV average line too I suppose.

**Comment by z3tt** [comment]
Added a new argument `.om_stats` to the `generate_report()` function. It takes the input `"average"` or `"median"` and will also apply the chosen statistic to the historical line in the trend chart. 

I have also added a conditional sentence stating which statistic has been used and a sentence explaining what the mean or median, respectively, represent and how they are calculated.

**Comment by z3tt** [comment]
I just realized that we need two different legend plots in case we have "median" specified (as the average is used for all other trendline charts). I've adjusted the logic for the HTML version. For the PDF version, I guess we have to add another legend plot at the end of the report in that case. Or change the labels to be more generally applicable...

**Comment by torv72** [comment]
Always something new🤣. I’ll differ to you on what looks best/easiest to generate. But I do agree we need something to specify the difference.  It would also be helpful to put a note somewhere reminding the client the difference between median and mean.  I learned that last week in talking with a client from Snowmass Club.

**Comment by z3tt** [comment]
Did you look at the short explainers that are added depending on the stats you choose?

Here are the respective text bits:

* "The following results show median values. The median value is the central point of the data, meaning half of the numbers in a list are smaller and half are larger than the median."
* "The following results show average values. The average, or mean, is the "typical" value in the data and is calculated by adding up all the numbers in a list and then dividing that total by the number of numbers."

Would you like to add another sentence explaining the difference? I am not sure if it is helpful to talk about a statistic that's not used. I'd say we only need another sentence explaining the difference between mean and median in case median values are shown. Otherwise, it might confuse the readers?

**Comment by torv72** [comment]
I had not seen those. As I’ve been out of town and don’t have a laptop. When I get back I will do a Git pull on Saturday and take a look at it. Below is something that could work???  Not sure. 

1. Median: The middle value in a sorted list of numbers. Half the values are below the median, half are above.
Advantage: Less affected by extreme outliers. 
Disadvantage: Doesn't consider all data points.

2. Mean (Average): Calculated by summing all values and dividing by the count of values.
Advantage: Uses all data points in its calculation.
Disadvantage: Can be skewed by extreme outlier.

**Comment by torv72** [comment]
I agree with you as well that it probably is not helpful to mention another statistic that isn’t being used.

**Comment by z3tt** [comment]
As discussed, I have added the note to the OM section in the executive summary, styled as italic. Not sure it makes sense to show it in case average values are used (?). What do you think?

![Screenshot 2024-10-01 at 00 00 28](https://github.com/user-attachments/assets/891e27e1-1794-4c2a-be51-546084537998)

**Comment by torv72** [comment]
That makes sense and works for me.  So the note will only show up if I choose median.  Otherwise the mean (average) is assumed.  Let’s roll with it!

**Comment by z3tt** [comment]
Currently, both show up but I'll adjust it to only show up in case `.om_stats = "median"`.

**Comment by torv72** [comment]
I just thought of something.  Not sure how difficult it is to do.  When I just wrote the report for Maroon Creek Club, I felt it necessary to include the Average measurements even though I set it up to do the Median.  I didn't want the client to be confused.  Long term I think the median is the right direction to go with all measurements.  It is nice to have the average available if I need it.  

I showed the average manually via the txt file.  

 I'm wondering if we could add a "both" to the function where if I chose that it would show both the median and the average at least in the Executive Summary.  Graphically I'm not sure we need to show both.  

I fear that now I wonder if I need to do this for the nutrients as well.  Would this be a simple setup in the generate_report function or does become very complicated?

Maybe I am opening up a "can of worms" as they say here but I need to be consistent.

**Comment by z3tt** [comment]
I will check if that's a simple change in the executive summary. Of course, it depends on your clients' needs but I don't think it's a good idea to put in visualizations for both, median and mean. And merging them (i.e. have both, the median and mean summaries as big dots plus trend lines) also doesn't sound like a good idea. If you think median is much more meaningful, my take would be to report median everywhere with the average results in the overview (as you've suggested).

**Comment by torv72** [comment]
I 100% agree. I don’t want to go down the road of mixing them (mean and median). Guys really focus on these numbers and for the organic matter testing the median is probably the best moving forward.  However as I transition existing clients at least this first time, I found myself wanting to at least in writing show them what they were use to, the average as there is a difference.  The workaround I did for Maroon Creek Club worked.  It was simple enough. Definitely don’t want to go down a rabbit hole here🤣

**Comment by z3tt** [comment]
It's not super-easy to implement. Would it be okay if it always shows a summary for median and mean values in case you choose `.om_stats = "median"`? That should simplify things a lot.

**Comment by torv72** [comment]
Yep. That works.

**Comment by z3tt** [comment]
Puh, it's not that straightforward in that case as well, unfortunately. We nevertheless have to run a big chunk of code twice and adjust the reporting of the values. Before, I was simply replacing the "old" average column with median values, using the same column name. Now, we'd have to handle two columns and always have to decide to use one or both, and in the latter case combine the comments. Or we would need to run it multiple times but I am not quite sure how to make it work seamlessly.

I see quite some challenges ahead, so let me know if you'd like me to proceed with this.

**Comment by torv72** [comment]
Let’s hold off then. I can easily run an “average” report and copy the text from the txt file that is generated. Then run the “median” version of the report and paste the text in it. No worries.   Thanks for checking though.

**Comment by z3tt** [comment]
Okay. As I have updated the naming convention for the executive summary files, it also nicely saves both into two separate files. Hope that simplifies the workflow. I also changed the naming logic for the reports (but guess you've noticed that already). Let me know if yo udon't like it or would like to apply a different logic.
