### ISSUE TITLE
Add an intro block to HTML version

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#38]
I recall that you'd like to add a note on the interactive parts of the HTML report that clients do not miss this feature or even search get annoyed that the detailed information is missing in this version. I also never really liked the placement of the liability waiver.

How about a "real" header a.k.a short introduction before the executive summary? Something like this maybe:

![Screenshot 2024-09-23 at 21 52 45](https://github.com/user-attachments/assets/9d20c085-9cc2-4889-b348-24355a443e61)

What do you think @torv72?

**Comment by torv72** [comment]
Yes. I recall that conversation. I think having that short introduction is a good idea and it saves me from having to explain it or put it in an email.  For some of these guys, it will not be intuitive that it is an interactive document. Remind me.  For the html version, will a chart appear similar to that on the pdf version  we have of the Organic Matter readings?

**Comment by z3tt** [comment]
Feel free to share one of your email template texts or any rewording of my first showcase draft and I'll update it accordingly. 

This intro block is only part of the HTML version; in the PDF version we have the title page with the client name, date, and your name, plus the liability waiver after the executive summary.

The charts in both, PDF and HTML versions , should be the same except that the first are static and the latter are interactive. I am working on the sand fraction visualization (similar to what you've shared in #28) and there will be a static and an interactive version. In the PDF report, also the table will be included. Not sure this is what you are referring to by "Organic Matter readings"?

**Comment by torv72** [comment]
Will do. When I get back home this weekend from (I’m currently in Yellowstone) collecting samples, I’ll do that. One thing I’d like to eliminate in the verbiage is anywhere where it says “TODO:….” It was meant for me as a reminder but I don’t need it.

**Comment by z3tt** [comment]
Done, all TODO notes have been removed.

**Comment by torv72** [comment]
How about something like this or similar:

# Interactive Agronomic Survey Report

## Maroon Creek Club 

**Date:** June 6, 2024
**Consultant:** Eric Foerster

Welcome to your interactive agronomic survey report. This HTML-based document offers:

1. **Interactive Charts:** Hover over elements for more details.
2. **Easy Navigation:** Use the table of contents to jump to specific sections.
3. **Responsive Design:** Optimized for various devices.

For the best experience, use a modern web browser and explore the interactive features. If you have any questions, please contact me directly.

Thank you for choosing my agronomic consulting services. I trust this report will provide valuable insights for your property management and improvement strategies.

**Comment by z3tt** [comment]
I've added the degrees to your name and linked the executive summary plus a bit of rewording (as we don't have a table of contents which was mentioned before). 

![Screenshot 2024-10-01 at 00 00 28](https://github.com/user-attachments/assets/7ec36fa5-44a5-49d2-8363-5c6ac4140060)

**Comment by torv72** [comment]
Try sending that screenshot again for this issue #38.  The screenshot you sent is the italic verbiage if the median is used.  You already sent that screenshot.

**Comment by z3tt** [comment]
Oh, you are right. here is the correct screenshot:

![Uploading Screenshot 2024-10-01 at 00.01.43.png…]()

**Comment by z3tt** [comment]
Oh, you are right. Here is the screenshot that I've meant to share:

![Screenshot 2024-10-01 at 00 01 43](https://github.com/user-attachments/assets/134dcbe9-6bf4-477e-90ef-9312c7229e1a)

**Comment by torv72** [comment]
That works!
