### ISSUE TITLE
Flextable error when including Sand Fraction in report

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#39]
I'm back in town.  I pulled the latest updates.  I think we are getting closer!  Maybe you are aware of this or maybe not.  When I put TRUE in for .include_sand_fraction = TRUE under he generate_report and I run the script, I get the following error message:

Error in `fp_border()`:
! could not find function "fp_border"
Backtrace:
  1. flextable::height_all(...)
 25. flextable::border_inner_h(...)
Called from: signal_abort(cnd)

Quitting from lines 10-125 [sf-table] (./templates/sand_fraction_testing.Rmd)

Quitting from lines 339-346 [sf-results] (report.Rmd)

Obviously when I put FALSE in, I don't get the error but I'm also not trying to generate a sand fraction report and everything is generating as it should!

**Comment by z3tt** [comment]
Fixed during the call
