### ISSUE TITLE
PDF Formatting Issue Water Testing

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#40]
This is a format issue.  I just ran a generate_report for Aspen Golf Club.  Everything looks great on the PDF except the Water Testing.  I attached what I see.  Notice the black "Irrigation" in the top left and the Trends Over Time | Irrigation header should be on a new page. 
[TORV-report_Aspen-Golf-Club_2024-09-27 (dragged).pdf](https://github.com/user-attachments/files/17197466/TORV-report_Aspen-Golf-Club_2024-09-27.dragged.pdf)

Here is the function:

```
generate_report(.site_name = "Aspen Golf Club",
                .zip_code = 81611,
                .date_sample_submitted = "2024-09-27",
                .start_date = "2018-01-01",
                .om_seasons = "all",
                .om_stats = "median",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "Yes",
                .include_sand_fraction = "No",
                .draw_beeswarm = "No",
                .output = c("pdf", "html"))
```

**Comment by torv72** [comment]
Good news on the page issue.  Better watch out!  I'm coming for your job!   I added a \newpage command to the water test template.  I pushed it on Git.  The black "Irrigation"....I'm wondering if you meant it to be there now.  I see code.  I didn't touch it.  

I had fun tonight actually just writing some stuff for the report.  I'm very happy with how things are looking.  Thank you!!!

**Comment by z3tt** [comment]
Great you were able to code it yourself, awesome! The label always has been there but the size should be zero and the color white os it's invisible (it serves as a header for navigation in the HTML as the section images can't be used as quick links). I'll look into that.

**Comment by z3tt** [comment]
Hm, didn't touch this but I think we can remove it. At least it's not used for navigation and the header image states what this is about anyway. 

Can't test it for this specific report as I am missing the latest data but should be fine.

**Comment by torv72** [comment]
Just ran a new report and you fixed it.  I'll close this.
