### ISSUE TITLE
Need to make Sand Fraction Report "linked" in HTML version of the report

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#41]
When I have a Sand Fraction table or eventual graphics, we need to have it linked like the other headers in the Executive Summary.  Right now I am just manually entering Sand Fraction in the txt file as ### Sand Fraction if I am including it in the report.  Presently it is not be auto generated like the other headers are.

**Comment by z3tt** [comment]
I'm going to implement this in the next iteration, no problem.

**Comment by z3tt** [comment]
As we currently do not feature sand fraction in the executive summary, this is not possible. If you'd like to have a summary, we'd need to work on that first.

**Comment by torv72** [comment]
Yes.  I think we need to have a header for Sand Fractions under the Executive Summary  if it is part of the report.
