### ISSUE TITLE
PDF Growth Potential Bar Chart

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#43]
Question.  I've been writing reports both in HTML and PDF.  I just noticed in the PDF version the Growth Potential Bar Chart looks to be "cutoff" for a lack of a better term.  Notice how the scale on the left side only shows 50%.  In the old PDF version (I have attached an example for you) it shows the full scale and percentages.  Does the new version need a slight adjustment in the PDF version?  Just wanted to get your thoughts on this.

[TORV-report_Snowmass-Club_2024-09-12 (dragged).pdf](https://github.com/user-attachments/files/17266377/TORV-report_Snowmass-Club_2024-09-12.dragged.pdf)
[TORV-report_Dominion-Meadows-Golf-Club_2024-10-04 (dragged).pdf](https://github.com/user-attachments/files/17266379/TORV-report_Dominion-Meadows-Golf-Club_2024-10-04.dragged.pdf)

**Comment by z3tt** [comment]
The horizontal grid lines only show the relevant thresholds, i.e. 20% and 50%. As the bars **should** be labelled, there is no need to add more labels to the scale. At least, that's what we have decided on back then and I personally prefer to have as few grid lines as possible.

But this is a good reminder that I need to make the direct labels work for the static version.

**Comment by torv72** [comment]
Your memory is better than mine!   Direct labels work for me.

**Comment by z3tt** [comment]
The static version now has direct labels. I have excluded those in case there is zero growth potential but one could add a note. Values look a bit weird in my opinion but are technically fine. I thought of a "none" label without printing the 0.0% value but blank looks best and seems intuitive enough (?)

![Screenshot 2024-10-07 at 17 08 39](https://github.com/user-attachments/assets/9bd00416-ced0-48d4-82e4-1a1b3b64f4b7)

*Version with "none" labels to be more explicit:*
![Screenshot 2024-10-07 at 17 17 28](https://github.com/user-attachments/assets/f1623cb5-bc18-4dd3-873f-9b0dc1a57f51)

**Comment by torv72** [comment]
This works. No need for a note if “0” and agree to leave it blank if it is 0.0%.  It is intuitive enough.
