### ISSUE TITLE
New Error after  Git pull with base

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#46]
Just pulled and now getting the following error....

I found the following soil types in the database: GREEN, TEE, FAIRWAY.
❗ I didn't find any water types in the database.
🗂️ I found the following OM types in the database: GREEN, TEE.

❓ Does that seem correct, or do you want to exit to investigate the database before running the rest of the report?
Type c for correct and hit ENTER to proceed, or hit any other key followed by ENTER to exit now.c
Error in `if (max_n_dates_per_sample > 1) ...`:
! the condition has length > 1
Backtrace:
 1. base::source(here("aux-scripts", "om-calculations.R"))
 3. base::eval(ei, envir)
 4. base::eval(ei, envir)
Called from: signal_abort(cnd)
Browse[1]> 

Quitting from lines 489-503 [prepare-element-tables-and-auto-comments] (templates/setup.Rmd)

Quitting from lines 25-28 [setup] (report.Rmd)

here is the function:

generate_report(.site_name = "Maroon Creek Club",
                .zip_code = 81611,
                .date_sample_submitted = "2024-09-18",
                .start_date = "2017-01-01",
                .om_seasons = "season",
                .om_stats = "median",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "Yes",
                .draw_beeswarm = "Yes",
                .output = c("pdf", "html"))

**Comment by torv72** [comment]
I'm wondering if it is a package issue???  renv:status says everything is in sync though.  

Just an FYI...When I try to pull, it says everything is up to date.

**Comment by z3tt** [comment]
No, it's something I've just implemented which seems to fail in case multiple sampling types have the same number of sampling dates. I run into this as well, fixed it in the meantime.

Maybe it makes sense to return to a main and a development branch so you can work with the tested main and I can continue working on the codes.
