### ISSUE TITLE
Minor Formating for when OM Accumulation rates are calculated

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#47]
I confirmed the OM accumulation calculations are working and are being included in the reports when I ask for them!!!  Everything looks good.  Wondering if we could add a small header "OM Accumulation Rates and Topdressing Recommendations" and then the bulleted list would show up.  Wondering if we "bold" GREEN and TEE or whatever the area is?  Just to make look a little nicer and easier to read???  I attached a snapshot of what the report looks like right now in PDF form.  You can see the last line on the first page is "GREEN" and then the second page is the rest of the output.

It seems to me that the first two bullet points are the organic accumulation rates for GREEN and TEE.  Then the next set of bullet point is the amount of sand topdressing being recommended.  I'm wondering if it would read better if we kept both GREEN calculations together and both TEE calculations together?   

So this is just a styling issue. Whatever you think looks best and reads well and isn't too difficult to implement.

<img width="934" alt="Screenshot 2024-10-08 at 1 37 39 PM" src="https://github.com/user-attachments/assets/d8f59ec8-1ea3-4360-a59e-e813b1353a47">

**Comment by torv72** [comment]
One additional format request. It look like the answers I get for the amount of topdressing sand that is recommended to apply are rounded numbers. 

Any chance to have it so that it does not round and gives me an answer to the nearest 1/10?  For example I believe the true GREEN recommendation is actually 2.2 mm. Right now it shows 2 mm.  I think it's rounding down in this case.

**Comment by z3tt** [comment]
I have added the headers, decided to use two not a combined title (I found the repetition of the same soil types in the same table confusing). I've put in random values but it seems to display digits for the sand addition. 

![Screenshot 2024-10-14 at 17 21 17](https://github.com/user-attachments/assets/18d13caf-66a0-4678-9668-78e0b6e5a879)

Can you test yours again? If it doesn't work, can you send me the inputs you're using?
