### ISSUE TITLE
Growth Potential Bar Chart in HTML no longer showing values when you hover over bar

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#48]
Not sure if you are aware or not but in the HTML version of the report, the values no longer "pop up" when you hover over the bar chart in the growth potential section of the report.  I will email you this separately as I can't attach an HTML to GitHub.

**Comment by z3tt** [comment]
My apologies, I was rewriting some code to simplify the sourcing and missed calling the interactive version here. Fixed.

**Comment by z3tt** [comment]
Hey Eric, while looking through the reports I found myself wondering if including the 100% explicitly makes sense as we mention the 100% value as "best outcome". Here is how it'd look like:

*PDF Version:*
![Screenshot 2024-10-14 at 16 20 00](https://github.com/user-attachments/assets/d4a3d683-f24e-4fae-85a8-10ad1ebd3f5e)

*HTML Version:*
![Screenshot 2024-10-14 at 16 31 04](https://github.com/user-attachments/assets/a6abc29d-04de-422c-a7b5-27086c5b5ee8)

**Comment by torv72** [comment]
I think we can do without now that the labels are there.

**Comment by torv72** [comment]
Maybe I misunderstood.  Are suggesting keeping the 100% line or removing it completely?Sorry for the confusion.

**Comment by z3tt** [comment]
Currently, only the 10% and 50% grid lines are shown to indicate the thresholds. The maximum height of the chart is based on the maximum value (here July). The version I've suggested here always goes up to 100% and has another grid line and label to indicate the max. 

Allowing the viewer to see the maximum value might be a good idea as (a) we mention that value in the text and (b) one can see the difference between the monthly outcome and the highest possible score directly. On the other hand, the version without the 100% line makes better use of the available space (but not so much an issue here).

**Comment by torv72** [comment]
Understood and thanks for that explanation.  Let’s keep it as you have designed with the 100% in. Thanks!
