### ISSUE TITLE
Need to Update the Total Organic table to reflect the median values if "median" is chosen

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#49]
I just ran a test report and everything is working fine.  However, when I choose "median" in the generate report function, the table in the Total Organic Matter part of the report should reflect the "median" values.  It looks like it is not and that it is reflecting the "average" values.  We just need to update that.  I have attached a copy of the report showing the what the Executive Summary says and then the corresponding Total Organic Matter table.  Again, you will notice no issues with "average".  However you will notice in the median example that the Executive Summary is correct but the Total Organic Matter table is not and showing average.  It does look like the graphs are correct albeit they are showing rounded numbers versus the exact number like the Executive Summary shows.

[TORV-report_The-Briarwood_2024-10-04-MEDIAN.pdf](https://github.com/user-attachments/files/17334349/TORV-report_The-Briarwood_2024-10-04-MEDIAN.pdf)
[TORV-report_The-Briarwood_2024-10-04-AVERAGE.pdf](https://github.com/user-attachments/files/17334351/TORV-report_The-Briarwood_2024-10-04-AVERAGE.pdf)
[TORV-report_The-Briarwood_2024-10-04-AVERAGE2.pdf](https://github.com/user-attachments/files/17334353/TORV-report_The-Briarwood_2024-10-04-AVERAGE2.pdf)
[TORV-report_The-Briarwood_2024-10-04-MEDIAN2.pdf](https://github.com/user-attachments/files/17334355/TORV-report_The-Briarwood_2024-10-04-MEDIAN2.pdf)

**Comment by z3tt** [comment]
Fixed. I've also switched the order of the columns as usually time increases from left to right. If you prefer the previous version (most recent results in first column), let me know.

**Comment by z3tt** [comment]
I also have updated the naming logic for the generated reports to include the season and statistic used for the OM section (following the naming philosophy used for the exec summary txt files).

**Comment by torv72** [comment]
I thought it was a German thing🤣Good job.
