### ISSUE TITLE
Organic Matter FAIRWAY update y ranges for the most extreme

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#5]
Easy fix for you to update the extremes on the Y axis for Organic Matter FAIRWAY.  The labels needed adjusting.

**Comment by z3tt** [comment]
I have added some logic to check if any of the two points that get labeled are extreme values and the scale range is adjusted accordingly. 

Here are the two outputs for the "Sonnenalp", the first with no extreme minimum values for the last two measurement dates and the one with only two test dates and thus the most extreme values possible:

![om_plot_GREEN](https://github.com/torv72/torv-reports-v4/assets/7523556/e0f7daf1-9036-438c-b4bf-262d1efd53c0)
![om_plot_FAIRWAY](https://github.com/torv72/torv-reports-v4/assets/7523556/70f75829-37ff-4b34-9afc-dca3462455d8)

Commit 5a39dcf4aaefb8dbc0ed4f27853d5fd420cd6d15 solves this issue.
