### ISSUE TITLE
Need slight adjustment at the OM 4-6 cm portion of Sand Fractions Table

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#50]
Probably just need to add one or two spaces between the bar chart and the sand fraction table so that the 4-6 cm moves down and is with its section on the next page. I attached the report as I am seeing it right now and you can see the 4-6 cm by itself on the page versus being with the rest it's "section"
![image](https://github.com/user-attachments/assets/54592558-5be3-4733-80f7-1bc4e4d54093)

**Comment by z3tt** [comment]
I was already working on the spacing, it is work in progress. I am going to add the detailed overview plots today or tomorrow. 

Do you actually also intend to add some text here? Currently, it is only charts and tables. If so, feel free to draft some general information. If you'd like to display numeric key metrics from the analysis, indicate it as well.

**Comment by torv72** [comment]
I think any text I add will go in the Executive Summary under the Sand Fractions Header.  I think the only thing I want to add is a “footer” referencing USGA specifications.  I’m traveling today and tomorrow so I can work on that verbiage when I get back tomorrow night.
