### ISSUE TITLE
Polished and interactive MLSN chart

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#51]
As I have the feeling you like all the details the MLSN "lollipop" chart is providing, I thought we should stick to it. Thus, I have reworked the original graphic to make it less colorful and easier to read. Changes include, among others:

* a neutral grey background
* color adjustments for the three categories (not the corporate SOIL orange as a warning color!)
* two-color versions for the categories to avoid the orange sticks and outline
* a slightly increased figure height to allow for more room, adjustments of the label positions

![Screenshot 2024-10-16 at 22 40 08](https://github.com/user-attachments/assets/55a14ecb-25dd-4d8c-a9de-80b28c7f151b)

I also have added interactivity to the version featured in the HTML report. It allows to see the detailed values for each nutrient x sample plus tooltips for the mean and the MSLN value (one could consider to remove the annotaitons on the very right in this case).

<img width="741" alt="Screenshot 2024-10-16 at 22 40 47" src="https://github.com/user-attachments/assets/307676ae-f9dc-4ce9-add1-4e1b0193935f">

**Comment by torv72** [comment]
Looks good and fits the “color theme” of the report.
