### ISSUE TITLE
The word "Approach" popping up in HTML version of Measurement Results and MLSN Values chart

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#52]
I noticed in the HTML version of the report that when under the "Measurement Results and MLSN Values" chart that when you hover over any point it says "Approach" no matter if it is in Green or Tee or Fairway sections.

**Comment by z3tt** [comment]
Well spotted, fixed 👍 Until now, I haven't realized that stating e.g. "TEE" each time is actually pretty repetitive information as we are in the "TEE" section anyway. Anyway, maybe repetition is key here so viewers are not confusing the similar looking graphics.
