### ISSUE TITLE
Add Sand Fraction Paragraphs

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#53]
As discussed in issues #41 and #50 we need to add sand fraction results to the executive summary and some general information to the SF section. 

> I think we need to have a header for Sand Fractions under the Executive Summary  if it is part of the report.

> I think any text I add will go in the Executive Summary under the Sand Fractions Header.  I think the only thing I want to add is a “footer” referencing USGA specifications.

Waiting for your input here. Alternatively, we can add it together during a meeting.

**Comment by torv72** [comment]
The footnote under each chart and the table would be as follows which is from a standard text in the golf course industry:

> Recommended ranges from the USGA Recommendations for a Method of Putting Green Construction, 2018 Revision

I think for text under the Sand Fractions part of the Executive Summary we could put a couple of “place holder” lines of text/gibberish/latin.

**Comment by z3tt** [comment]
We could also add that information in a short section intro paragraph. That would add a bit of text which IMO looks better plus we are not going to repeat the same information plus we could even link the source.

**Comment by torv72** [comment]
Good idea.  I’ll work on one and get it to you.

**Comment by torv72** [comment]
Here is a paragraph that I think we could use.

The sand fraction analysis examines the composition of the golf course greens in the top 6 cm of the surface. The S022 lab test analyzes organic matter samples after they have been washed from three depths: 0-2 cm, 2-4 cm, and 4-6 cm. These samples are sieved according to the United States Golf Association (USGA) specifications for sand particle sizes, as outlined in "USGA Recommendations for a Method of Putting Green Construction, 2018 Revision." The results show the distribution of sand fractions at each depth, providing information about the green's physical properties in its upper layer. This data helps in assessing factors such as water movement and surface firmness in the most active part of the green's profile. The analysis offers insights into the surface and near-surface conditions, which is useful for evaluating the current state of the green's top layer and for making informed decisions about its maintenance.

**Comment by torv72** [comment]
Question....Would it make sense to remove the "Total Organic Matter" from the header portion of the report and just have it titled "Sand Fraction"???   Yes, the sand fractions do come from the organic matter samples but they really two different things.  One is sand and the other is organic matter.  We could give the header it's own stand alone color.

**Comment by z3tt** [comment]
The sand fraction section with the intro paragraph:

![Screenshot 2024-10-18 at 16 25 08](https://github.com/user-attachments/assets/f5078c50-56ee-4f63-876c-8e94a49e69ef)

**Comment by z3tt** [comment]
No problem, I can adjust the header. The only "problem" is that we are running out of colors. Should I pick a new one? Maybe a brownish color?

**Comment by torv72** [comment]
That works!  The word “washed” appears on the third line down.  I meant to say “ashed” the samples are burned.

**Comment by torv72** [comment]
Yes.  I was thinking a brownish or tannish color.

**Comment by z3tt** [comment]
I've adjusted the typo, section header text, and section color.
![Screenshot 2024-10-18 at 16 59 56](https://github.com/user-attachments/assets/f24c0988-2383-4c2a-9ad8-c9966d7cd1b0)
