### ISSUE TITLE
Error when there is ONLY Organic Matter Testing to Report

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#55]
I have a new situation here.  I have a client that is only doing Organic Matter testing.  He has done it in the past but normally there is soil testing involved.  Not this time.  When I try to create the report, it stops at the growth potential model and is giving me an error.  I think it is expecting that a growth model needs to be created for whatever reason and I'm getting the error.  I am then wanting to calculate the OM but I can't get past the error.  I will send you the updated MASTERDATABASE via email that has the data.  Below is the function. There is actually two golf courses on this property.  The function represents the first course.  I have also included the error that I am seeing.

generate_report(.site_name = "The Club at Flying Horse North Course",
                .zip_code = 80921,
                .date_sample_submitted = "2024-10-17",
                .start_date = "2017-01-01",
                .om_seasons = "season",
                .om_stats = "average",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "No",
                .draw_beeswarm = "Yes",
                .output = c("html"))

Here is the error I am getting:

❓ Would you like to calculate OM accumulation rates?
Type y for yes or n for no and hit ENTER. y

💪 Perfect, we're all set up! I'll compile the rest of the report now, wait a moment.

output file: setup.md

  |............................                                                  |  36% [exec-summary]        

❗ An executive summary for this site already exists. Sourcing the file "exec-summary_The-Club-at-Flying-Horse-North-Course_2024-10-17_season_average.txt" in the "report" directory.
    - To add comments, open the txt file, modify its content, and generate the report again.
    - To create a new auto-generated executive summary for this site, please delete the txt file, and rerun the report generation.

  |.............................................                                 |  58% [turf-growth-rds-html]Error:
! object 'growth_potential_plot' not found
Backtrace:
 1. ggiraph::girafe(ggobj = growth_potential_plot)
Called from: signal_abort(cnd)
Browse[1]>

**Comment by torv72** [comment]
Just to reaffirm, this seems to be a special case issue.  Everything else has been working just fine so far.

**Comment by z3tt** [comment]
Thanks for reporting, it's fixed.
