### ISSUE TITLE
When Answering "Yes" to calculating OM accumlation rates nothing happens

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#56]
Good morning.  I just tried running a report for a client.  Normally I answer "No" when being asked if I wanted to calculate OM accumulation rates.  However, for this client I would like to.  When I answer "Yes", the program skips over the expected questions that need to be answered thus I can't calculate the accumulation rate.  

Here is the generate report function:

generate_report(.site_name = "The Club at Flying Horse North Course",
                .zip_code = 80921,
                .date_sample_submitted = "2024-10-17",
                .start_date = "2017-01-01",
                .om_seasons = "season",
                .om_stats = "average",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "No",
                .draw_beeswarm = "Yes",
                .output = c("pdf","html"))

**Comment by torv72** [comment]
Interestingly, when I use Maroon Creek Club as the .site_name, it works though.

**Comment by z3tt** [comment]
It should ask you again for inputs. Can you check if this is the desired logic?

**Comment by torv72** [comment]
What is happening is that it does ask me if I want to calculate the OM accumulation rate.  I answer with a “y”.  But then there are no further questions asking for the inputs.  It goes right into producing the report.  So I never get a chance to enter any further information.

However if I run a Maroon Creek Club report, I do get the the further questions for input.  It’s like Maroon Creek Club is the only one it is working for.  I just tried it for another client “The Valley Club Irwin” and again it does ask me if I want to calculate the OM and I say “y” but then I do not get the follow up questions like I do with Maroon Creek Club.

In this case I was trying to run a report for “The Club at Flying Horse North Course”.

**Comment by z3tt** [comment]
Did you make sure to pull the latest changes? It should ask you again when running “The Club at Flying Horse North Course”. 
(The reason was that this client only features one sample type, and I missed to apply the same logic then.)

**Comment by torv72** [comment]
I had not pulled it.  Sorry.  BINGO!   We have success!  Thank you.

**Comment by torv72** [comment]
Sorry.  Still have a problem here.  It is not printing the results now in the report.  I goes thru all of the questions but nothing is reported.

**Comment by z3tt** [comment]
Fixed now, hope it works as expected.

**Comment by torv72** [comment]
Unfortunately it did not.  It goes thru all of the questions as expected now put does not print out the results in either PDF or HTML.

Here is a copy of the PDF.  There is a blank page now.

[TORV-report_The-Club-at-Flying-Horse-North-Course_2024-10-17_season_average.pdf](https://github.com/user-attachments/files/17465952/TORV-report_The-Club-at-Flying-Horse-North-Course_2024-10-17_season_average.pdf)

**Comment by z3tt** [comment]
For me it works, the summary of the OM acucmulation rates is added to the executive summary:

![Screenshot 2024-10-22 at 11 13 27](https://github.com/user-attachments/assets/b71d57e8-ef16-40a4-be23-5d677f37fa0e)

Did you make sure to pull the latest changes?

The blank page must have been there before since I moved the liability waiver to the end of the page; I have now removed the \newpage command and it seems to work.

[TORV-report_The-Club-at-Flying-Horse-North-Course_2024-10-17_season_average.pdf](https://github.com/user-attachments/files/17473415/TORV-report_The-Club-at-Flying-Horse-North-Course_2024-10-17_season_average.pdf)

**Comment by torv72** [comment]
Good morning.  I think I know what happened.  I failed to delete the old txt file that was generated when things were not working.  Hence that is why I kept seeing the same thing.  My apologies.  I'm quickly realizing I have work to do on file management.

I am seeing the same thing as you are now.  

1.  Can you move the "bolded" OM Accumulations Rates:" that appears along the 4-6 cm depth line down one or two lines.  It should be a header.  

2.  There should be some additional text from the calculations underneath the Topdressing Recommendations.  I took a screenshot of what it should look like from a Maroon Creek report I did back in September.
<img width="2560" alt="Screenshot 2024-10-22 at 5 36 15 AM" src="https://github.com/user-attachments/assets/48708580-735d-421f-a630-af5c395da7fe">

**Comment by z3tt** [comment]
1. Done.
2. Not sure what is going on here to be honest. It's the same logic as for multiple types, so it should show up. Diving into those commentary codes, but still not feeling overly confident to adjust codes.

As a side note, there is an argument that I've added for my convenience that might be helpful for you, too. If you set `.overwite = "Yes"`, it will always overwrite the executive summary txt file (usually not recommended in case you're adjusting those files but good for testing).

**Comment by torv72** [comment]
No luck on my end.  The code takes me thru all of the questions like it should.  No problem there.  The results and commentary is just not showing up on the final report.  I did do a pull and everything is up to date.  

<img width="827" alt="Screenshot 2024-10-22 at 6 42 40 AM" src="https://github.com/user-attachments/assets/abbc5fb9-7633-452c-86fd-d39ec1f4a28a">

**Comment by z3tt** [comment]
I am currently working on the water section and will look into this after that.

**Comment by z3tt** [comment]
For the example, it works for me again (likely those are non-sense values but it works). Please test if it works as expected and reports the correct types and values.

![Screenshot 2024-10-23 at 12 54 13](https://github.com/user-attachments/assets/e470be44-bde4-4d02-bad3-b2e4f81dd766)

**Comment by torv72** [comment]
OK. I think we have some success here!  The only little bug I am seeing for me is if you notice there is a bolded "OM Accumulation Rates:"  that just needs to be moved down a line.  Right now it is at the end of the 4-6 cm bullet point.

I don't know what you did but thank you!

<img width="843" alt="Screenshot 2024-10-23 at 6 28 50 AM" src="https://github.com/user-attachments/assets/86dbbe94-dbb3-42f3-b8cf-8f48ea0e5fa4">

**Comment by z3tt** [comment]
Oh yeah, well spotted. Going to fix it!

**Comment by z3tt** [comment]
Fixed with latest commit.
