### ISSUE TITLE
New Bug when running report when you are able to take a look

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#57]
Ran into this bug when running a new report.  It looks like an extra ")" in the code but I can't find it.  
```
generate_report(.site_name = "Adobe Creek National Golf Course Monument",
                 .zip_code = 81521,
                 .date_sample_submitted = "2024-10-08",
                 .start_date = "2017-01-01",
                 .om_seasons = "season",
                 .om_stats = "average",
                 .warm_or_cool = "cool",
                 .acid_extract = "Mehlich",
                 .include_results_interpretation = "No",
                 .include_sand_fraction = "No",
                 .draw_beeswarm = "Yes",
                 .output = c("pdf","html"))
```
Error during wrapup: The file 'report/report.Rmd' does not exist.
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Browse[1]> 

Quitting from lines 162-170 [unnamed-chunk-29] (report.Rmd)

Quitting from lines 311-325 [soil-results] (report.Rmd)

```                                                                                                                                                                               
# And another example with a different site, median values, sand fraction results,
# no beeswarms in the trendline charts, and both HTML and PDF as output:
generate_report(.site_name = "Adobe Creek National Golf Course Monument",
                 .zip_code = 81521,
                 .date_sample_submitted = "2024-10-08",
                 .start_date = "2017-01-01",
                 .om_seasons = "season",
                 .om_stats = "average",
                 .warm_or_cool = "cool",
                 .acid_extract = "Mehlich",
                 .include_results_interpretation = "No",
                 .include_sand_fraction = "No",
                 .draw_beeswarm = "Yes",
                 .output = c("pdf","html"))
```

processing file: report.Rmd
  |..........                                                                                                        |   9% [setup]               

processing file: templates/setup.Rmd

🗂️ I found the following soil types in the database: GREEN, FAIRWAY.
🗂️ I found the following water types in the database: 18 1/2 ROAD.
🗂️ I found the following OM types in the database: GREEN.

❓ Does that seem correct, or do you want to exit to investigate the database before running the rest of the report?
Type c for correct and hit ENTER to proceed, or hit any other key followed by ENTER to exit now.c

I have only found one date for OM data. I will not ask you about the OM accumulation rate.

I found analyses for the following types of soil in the database: GREEN, FAIRWAY.

❓ Do you want to use the default Grass Maximum N/month lb/1000 sq ft values for the deficit tables?
Type y for yes or n for no and hit ENTER: y

✅ Great, I'll use these default values: GREEN = 0.5, FAIRWAY = 0.7.

💪 Perfect, we're all set up! I'll compile the rest of the report now, wait a moment.

output file: setup.md

  |.........................................                                                                         |  36% [exec-summary]        

❗ An executive summary for this site already exists. Sourcing the file "exec-summary_Adobe-Creek-National-Golf-Course-Monument_2024-10-08_season_average.txt" in the "report" directory.
    - To add comments, open the txt file, modify its content, and generate the report again.
    - To create a new auto-generated executive summary for this site, please delete the txt file, and rerun the report generation.

  |............................................................................                                      |  67% [soil-results]        Error in `parse()`:
! <text>:67:5: unexpected ')'
66:     )
67:     )
        ^
Backtrace:
  1. global generate_report(...)
 50. knitr::knit_child(text = ., quiet = TRUE, , envir = parent.frame())
 51. knitr::knit(..., tangle = opts_knit$get("tangle"), envir = envir)
 52. knitr:::process_file(text, output)
 55. knitr:::process_group(group)
     ...
 58. knitr:::eng_r(options)
 61. knitr (local) evaluate(...)
 62. evaluate::evaluate(...)
 64. evaluate:::parse_all.character(...)
 65. base::parse(text = x, srcfile = src)
Called from: signal_abort(cnd)
Browse[1]> 

Quitting from lines 162-170 [unnamed-chunk-29] (report.Rmd)

Quitting from lines 311-325 [soil-results] (report.Rmd)

**Comment by torv72** [comment]
I think you must have fixed this.  Everything is working again.

**Comment by z3tt** [comment]
Yes, it was a work-in-progress mistake. Great to hear that it works again!
