### ISSUE TITLE
Tool tip showing % symbol at the end of the values versus the correct unit

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#58]
Noticed in the tool tip that the % symbol is showing up at the end of values instead of say ppm for example.  Here is a screenshot of what I am seeing.

<img width="597" alt="Screenshot 2024-10-21 at 2 56 49 PM" src="https://github.com/user-attachments/assets/ea8be2af-a411-47f5-a58f-39c8801e056c">

Here is the report function:

generate_report(.site_name = "Adobe Creek National Golf Course Monument",
                .zip_code = 81521,
                .date_sample_submitted = "2024-10-08",
                .start_date = "2017-01-01",
                .om_seasons = "all",
                .om_stats = "average",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "No",
                .draw_beeswarm = "No",
                .output = c("pdf", "html"))

**Comment by z3tt** [comment]
Copy-paste mistake from the OM timeseries charts, fixed now.
