### ISSUE TITLE
Need to adjust the Organic Matter "Historic Average" line in the charts or Rename to TORV average

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#59]
I just ran a new report for a client, Bartlett Hills Golf Course.  This is their third time sampling with me. I noticed on the organic matter charts that the Historic Average line is way above their "average line".  I know we use the Historic Average in the soil nutrient charts and it looks good.  I think we were using the  "TORV average" in the OM charts which would explain why the line is way above Bartlett Hills's average.  Is there a way to label that line "TORV average" instead of  "Historic average"?  This is just for the Organic matter charts.  If it is not possible or not easy, then the alternative is move the lines to the actual true average of the client and then the line can remain named "Historic Average".  

This became easy to see now because of only three samplings.

<img width="1200" alt="Screenshot 2024-10-22 at 2 50 54 PM" src="https://github.com/user-attachments/assets/46990ab5-63dc-4bf6-b7a9-c04ed9b499cd">

I'll email you an updated MASTERDATABASE in case you want it.
Here is the function:

generate_report(.site_name = "Bartlett Hills Golf Course",
                .zip_code = 60103,
                .date_sample_submitted = "2024-10-21",
                .start_date = "2017-01-01",
                .om_seasons = "season",
                .om_stats = "average",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "No",
                .draw_beeswarm = "No",
                .overwrite_report = "No",
                .output = c("html"))

**Comment by torv72** [comment]
Another quick thought to resolve. Do we leave as is in the graphics but color the line that is there differently than the gray and then just modify the legend by adding the new line and color and labeling it "TORV Average"?  So there would be two types of average lines in the legend. 

The gray line still remains as it represents the clients average which is what we see in the soil nutrient trend over time graphics. 

Just a thought.

**Comment by z3tt** [comment]
If I understood you correctly, this is what you are looking for?
![Screenshot 2024-10-23 at 11 33 33](https://github.com/user-attachments/assets/b3109536-231f-4799-807d-461bcfde49ea)

**Comment by torv72** [comment]
Tested it that works!
