### ISSUE TITLE
No Issue. Just and FYI for you

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#61]
I updated the "header creator" chunk to increase the width from 5.6-5.8.  I had a client with a slightly longer header name and needed to fit it.  Just wanted you to know.  I pushed the change and here a screen shot.
<img width="1053" alt="Screenshot 2024-10-24 at 2 47 51 PM" src="https://github.com/user-attachments/assets/71b183a5-d111-464c-86cd-c40aa10b9b80">

Also not sure if you saw my earlier issue entitled MAJOR ISSUE.  I found the error.  The code chunk was commented out with "#" and this the soil testing wouldn't generate anything:). So I figured it out and made the changes and pushed.  I realized I closed the issue and wasn't sure if you would see it or not.

**Comment by z3tt** [comment]
Perfect. Does that mean that the text is broken into two lines? If so, could you share a screenshot please? I fear it will not look good and maybe we can come up with a different solution (even if it's only reducing the font size a bit)

And sorry about the soil section, I commented it to increase the iteration speed when working on the water section. Pardon.
