### ISSUE TITLE
Water Sampling Viz Updates

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#63]
Not an issue because I have been working on it myself and wanted to let you know. 

I had an oddball water sample that had values beyond what is normally seen. It was for the water Exit sample.  Specifically, chloride (357 ppm) and Sodium at 373 ppm.  Because of this, both values were not showing up on the viz at all.  So I set out to try and fix it myself.  Guess what?  I think did!  Hopefully.

Also, the SAR value in the Entry sample was showing up in the right spot correcly, however it was colored incorrectly I believe and the tool tip said it was a low value when in fact it was in the medium range.  (see below for a copy of the report function that generated this report).  I have also attached the PDF report.  Notice it says 1.3  and is in the medium and colored blue now which is correct. Before it was in the same spot but colored purple and was considered "low".  Guess what?  I think I fixed it:). Again hopefully.

[TORV-report_Wellshire-Golf-Club_2024-10-19_season_average copy.pdf](https://github.com/user-attachments/files/17527541/TORV-report_Wellshire-Golf-Club_2024-10-19_season_average.copy.pdf)

Anyways. I will push the changes I made.  I hope I haven't embarrassed myself and I hope you approve.  If you do not, feel free to fix it.  It will not hurt my feelings!

Here is the report function:  generate_report(.site_name = "Wellshire Golf Club",
                .zip_code = 80222,
                .date_sample_submitted = "2024-10-19",
                .start_date = "2017-01-01",
                .om_seasons = "season",
                .om_stats = "average",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "No",
                .draw_beeswarm = "No",
                .output = c("pdf","html"))

**Comment by z3tt** [comment]
Great work! Yes, the wrong labeling of the outcome is something I noticed too. It's due to the reversed order (low threshold is higher than high threshold) which breaks the logic. I already had implemented a solution, I'll test both and will one!
