### ISSUE TITLE
Your opinion on footer and lab logo

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#64]
Just wanted to get your opinion on a bottom of page footer that would have my contact information across the bottom of the pages.  It would read "TORV, LLC, 260 Woodruff Road, Glenwood Springs, CO 81601  +1.970.409.9874  eric@torv.me"   It would be smallish font. Maybe grey like the liability waiver.  

Also your option on including the logo of the laboratory I use. It would not be prominent. It would maybe have something say "Analysis provided by Brookside Laboratories, Inc".

I'll send the logo separately to your email. 

If you like the idea, please incorporate. If not, no worries!

**Comment by torv72** [comment]
I just realized it would be for the PDF.  Not sure how it would work on html.

**Comment by z3tt** [comment]
Exactly, that only applies to the PDF version. For the HTML, you'd add all this information to the header or intro section as there is no pagination.

![Screenshot 2024-10-28 at 16 32 42](https://github.com/user-attachments/assets/a302faaf-3076-40b5-89d3-c473a33ea8b3)

You can also get a header displaying the current section name (as in the screenshot above; let me know if you'd like that). 
Do you want to have page numbers or keep it clean?

**Comment by z3tt** [comment]
For the text + logo on the lab analyses: where you'd like to place it? Not in every footer I guess. Should we add it to the intro section (for HTML) and the title page or end of the report (for PDF)?

If you want to add it in the first place is a question you have to answer (if it's not a requirement by the laboratory anyway). It is definitely possible, although the images likely have to be included with two different logics based on the output format (means it involves try'n'error).

**Comment by torv72** [comment]
If page numbering doesn’t get in the way I think we keep it. For the text+ logo I think we put it on the title page for PDF and html intro as you suggested. Regarding the screenshot…sorry, am I missing something there?  It looks like what we have been doing which looks good.

**Comment by z3tt** [comment]
The screenshot is just to showcase the header and footer functionality. The footer should be fine (dealing with page numbers currently, unfortunately not as straightforward as I hoped), the header is optional.

**Comment by torv72** [comment]
No worries. If it is a nightmare to do it, let’s do what looks good and is easy to implement.  If that means no page numbering I’m ok with that. You’ve done a great job and I’ll defer to you on what looks best.

**Comment by z3tt** [comment]
Made it work, not with the section name but I think this way it's better anyway!

![Screenshot 2024-10-28 at 17 59 20](https://github.com/user-attachments/assets/4e429d94-7ad5-43c9-b95f-738af56d4bc7)

I also have removed the page number on the title page (see screenshot in next comment).

**Comment by z3tt** [comment]
Brookside mention and logo in the PDF version:

![Screenshot 2024-10-28 at 17 56 40](https://github.com/user-attachments/assets/1a726ab3-1558-4147-98ed-411e52630548)

**Comment by torv72** [comment]
Looks great!

**Comment by z3tt** [comment]
Brookside mention and logo in the HTML version:
![Screenshot 2024-10-28 at 20 36 35](https://github.com/user-attachments/assets/c2215d2d-a7f5-4349-a928-9cdbb0afc52d)
