### ISSUE TITLE
Multiple Issues maybe after Git Pull

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#65]
Good morning (my time).  I'm back from my travels and pulled the latest updated.  Unfortunately I've run into some errors that I've never seen before.

Here is the one that stops things immediately.

n `read_data()`:
! Argument 'svg' or 'css' must be a file path, url, or raw vector.
Backtrace:
 1. header_file_create("None", "Executive Summary")
 2. rsvg::rsvg_svg(...)
 3. rsvg:::rsvg_format(...)
 4. rsvg:::read_data(svg)
Called from: signal_abort(cnd)
Browse[1]> 

Quitting from lines 111-113 [exec-summary-header] (report.Rmd)

Here is the report function.

generate_report(.site_name = "Hemingway Golf Course",
                .zip_code = 80649,
                .date_sample_submitted = "2024-10-22",
                .start_date = "1997-01-01",
                .om_seasons = "season",
                .om_stats = "average",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "No",
                .draw_beeswarm = "Yes",
                .output = c("html"))

I also noticed some code in the report.Rmd is commented out. 

The Soil Testing chunk in 341 thru 354.

Also in setup.rmd

lines 28 thru 33 were also commented out.

**Comment by z3tt** [comment]
Argh! Sorry for missing (again) to reactive the soil section. I'll always remove it for testing to increase the time for generating the reports (not the best practice).

About the SVG error: I have cleaned the repository and removed the files that have been uploaded to GitHub but are featured in the gitignore file. Seems it also features some mandatory files (the icons for the headers) so I've add some exception rule for those to the gitignore. I hope it works now!

**Comment by torv72** [comment]
Good morning!   OK.  I just pulled again. and now I am getting this error.  I think you may have fixed the SVG error though!  Progress!


  |.................................................................                              |  68% [soil-results]        Error in `glue_data()`:
! A '#' comment in a glue expression must terminate with a newline.
Backtrace:
 1. base::cat(glue("## GREEN{#GREEN}"))
 2. glue::glue("## GREEN{#GREEN}")
 3. glue::glue_data(...)
Called from: signal_abort(cnd)
Browse[1]> 

Quitting from lines 5-6 [unnamed-chunk-15] (report.Rmd)

Quitting from lines 341-355 [soil-results] (report.Rmd)


Here is the report function:  generate_report(.site_name = "Hemingway Golf Course",
                .zip_code = 80649,
                .date_sample_submitted = "2024-10-22",
                .start_date = "1997-01-01",
                .om_seasons = "season",
                .om_stats = "average",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = "No",
                .include_sand_fraction = "No",
                .draw_beeswarm = "Yes",
                .output = c("html"))

**Comment by torv72** [comment]
I think I fixed it.  I changed line 5 in the soil_testing_table.Rmd to the following and got a report to render.

cat("## ", "{{sample_description_number_1}}", "{#", "{{sample_description_number_1}}", "}", sep="")

Feel free to close this if you think I fixed this correctly.

**Comment by z3tt** [comment]
Interesting, I did not run into this error but glad to hear it works for you now!
