### ISSUE TITLE
Minor color word change in 

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#66]
I missed this totally.  A client of mine had some fun with me and pointed this out.  Need to change the word colors to match the word colors if you know what I mean.  Notice how "Green dots" are in the red color and the "Red dots" are in the green color.  It should be reversed.

<img width="1127" alt="Screenshot 2024-10-31 at 2 47 33 PM" src="https://github.com/user-attachments/assets/97987860-342a-4b68-886f-cb000f6fc2c3">

**Comment by z3tt** [comment]
Already changed that in some previous commit, sorry for the mix-up.
