### ISSUE TITLE
Tiny Charts Not Appearing in the Report

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#67]
Not sure if you meant for the tiny charts to now render in the report or not but I am not seeing them in the final rendered reports.  However, I am now seeing the old version of the mean measurements in the reports.

This is what I am seeing.

<img width="1552" alt="Screenshot 2024-11-01 at 6 19 48 AM" src="https://github.com/user-attachments/assets/47a33d4d-1007-4621-b4ad-b812974479b5">

**Comment by torv72** [comment]
Nevermind.  Got it working.  I removed the original .txt file for Hemingway and it works!   

Now I think we just need to "turn off" the Mean Measurements section and I think we are good to go!

**Comment by torv72** [comment]
Ok. I figured out one way to "turn off" the Mean Measurements summary section.  I added "eval=FALSE" to lines 114, 118, 122, and 135 in the soil_testing_table_.Rmd.

I've run everything and all seems to be working!  

Feel free to change anything I did or correct me.  Otherwise we can close this.

**Comment by z3tt** [comment]
Again, strange that it shows up, I removed that section a few weeks ago (I mentioned it in another issue). `eval = FALSE` is the way to go here, well done!
