### ISSUE TITLE
Question regarding html behavior

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#68]
In the html version with the introduction of the tiny charts now, when I  click on the "Green" or "Tee", or "Fairway" in the Executive Summary it just recenters the page basically.  It doesn't take me anywhere else in the report like it use to.  Organic Matter still takes me to the other part of the report(Trends Over Time section)  as well as the Sand Fraction which takes me to the Sand Fraction graphs.

Just curious if that can be pointed to the Trends Over Time section like it use to be?  If not, no worries at all.

**Comment by z3tt** [comment]
Thanks for mentioning it, this might be due to me trying to fix the quick links in the PDF version. I'll investigate that. Not sure when the links broke in the PDF (I recall they were working a few weeks ago but noticed they are not active anymore a few days ago).

**Comment by z3tt** [comment]
Fixed.
