### ISSUE TITLE
Lookup Table for ZIP Codes

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#72]
Instead of passing the respective ZIP code as a function argument in `generate_report()`, we are switching to a lookup table that provides the ZIP codes for all known client courses. 

@torv72 Can you provide the list, preferably in the following syntax:
```
~site_name,          ~zip_code, 
"Maroon Creek Club", 81615,
"...",               ...
```

As discussed, we could also pass the codes via the MASTERDATABASE by adding another column. But if I understand correctly, that would still involve the step of searching for the respective ZIP every time you add a known client (?)

**Comment by torv72** [comment]
Let's see if this works.  These are my current golf courses that I work with.  I can always update the code when I add new ones.

~site_name,          ~zip_code,
"Adobe Creek National Golf Course", 81521,
"Adobe CreeK National Golf Course Desert", 81521,
"Adobe CreeK National Golf Course Mesa", 81521,
"Adobe CreeK National Golf Course Monument", 81521,
"Aspen Golf Club", 81611,
"Bartlett Hills Golf Course", 60103,
"Catamount Ranch and Club", 80477,
"Chipeta Golf Course", 81503,
"CommonGround Golf Course", 80010,
"Copper Creek Golf Course", 80443,
"Dominion Meadows Golf Club", 99114,
"Greeley Country Club", 80634,
"Hemingway Golf Club", 80649,
"Maroon Creek Club", 81611,
"Snowmass Club", 81615,
"Sonnenalp Golf Club", 81632,
"The Briarwood", 59101,
"The Broadmoor East", 80906,
"The Broadmoor West", 80906,
"The Club at Flying Horse Club", 80921,
"The Club at Flying Horse North", 80921,
"The Valley Club Irwin", 83333,
"The Valley Club Fazio", 83333,
"Three Crowns Golf Club", 82604,
"Wellshire Golf Club", 80222,

**Comment by z3tt** [comment]
Thanks! Exactly, once you'll get new clients, just add the new client name + zip code to the list specified in `report.Rmd` (let me know in case you prefer to set it inside `generate-report.R`).

**Comment by z3tt** [comment]
Done. In case a site name is not featured in the `zip_code_list` (make sure to use the exact same spelling to match the codes successfully), `generate_report()` will throw the error:

```
❌ Cancelling report generation as I couldn't find the site name in the ZIP code table.
❗ Please add the site to the zip_code_list specified in report.Rmd and rerun the report generation.
```

**Comment by z3tt** [comment]
Some things I've noticed, just making sure the information you've provided is correct.
- The zip code for Maroon Creek differs from that specified for the example report back then.
- The site name "Adobe CreeK" features an upper-case K.

**Comment by torv72** [comment]
Adobe Creek with a capital “K” was a typo.  I fixed in the report.rmd file.  

Maroon Creek zip is 81611.  The 81615 is Snowmass which happens to be basically next door.  So it is now correct in the report.rmd file.  No need to change anything.

**Comment by z3tt** [comment]
Great, good training session to get used to adjusting that list! Hope this enhancement makes things easier for you 🙌
