### ISSUE TITLE
New Main Branch + Documentation

### ISSUE THREAD

**Issue by z3tt** [torv72/torv-reports-v4#74]
As discussed, I have removed the old branches, moved the outdated DOCX version to a new branch, and turned the latest HTML+PDF version into the main branch. Please use this branch from now on if you need to generate reports. 

If you need to make changes, it may be a good idea to develop and test them on a different branch.

I also have added some documentation of the general workflow, the available function inputs (splitter by required and optional inputs) as well as some examples to the README. I have removed all the blah from the `eric.R` script so it makes it easy for you to run the functions.

As discussed, feel free to either adjust the code in that file every time or to add new reports to the top of the "list". The latter will allow you to go back to previous codes much easier (in case you want to check your inputs or rerun the report at a later point). 

Feel free to close this issue once you have inspected the new documentation.

**Comment by z3tt** [comment]
For the documentation, can you please provide the ID you use for Snowmass Club? I have added `.site_name_abbr` to the examples and as this should include the ID, I'd like having a meaningful input here.

**Comment by torv72** [comment]
The ID for Snowmass Club is 36644.  So the .site_name_abbr = 36644-snowmass

**Comment by torv72** [comment]
Everything appears to be working!!!!!  Thank you.

Quick question for clarification.  You mentioned "As discussed, feel free to either adjust the code in that file every time or to add new reports to the top of the "list". The latter will allow you to go back to previous codes much easier (in case you want to check your inputs or rerun the report at a later point).

Can you elaborate on "adding new reports to the top of the "list".  I understood the adjusting the code in the file but didn't know what you meant by "the latter" .  

Otherwise I think we are good to go!

**Comment by z3tt** [comment]
Great to hear we are all set for now!

Currently, there is one `generate_report()` call in the script `eric.R`. As you wish to track your previous reports, my suggestion during our last call was to keep the `generate_report(...)` code and simply add new reports above them.

When running your first report `eric.R` looks like this:

```
##------------------------------------------------------------------------------

# Step 1: Update Database ------------------------------------------------------
# Run the follopwing code to update your database.
source(here::here("aux-scripts/update-database.R"))
# Note: Make sure you don't have the file open, or you'll get an error.


# Step 2: Generate Report ------------------------------------------------------
# First, source the file to load the generate_report() function...
source(here::here("aux-scripts/generate-report.R"))

# ... and now run the function with the custom inputs:
generate_report(
  .site_name = "Maroon Creek Club",
  .site_name_abbr = "35873-maroon-creek",
  .date_sample_submitted = "2024-09-18",
  .start_date = "2017-01-01",
  .om_seasons = "season",
  .warm_or_cool = "cool",
  .acid_extract = "Mehlich",
  .include_results_interpretation = "No",
  .include_sand_fraction = "Yes",
  .output = c("pdf", "html")
)


# Optional Step: Generate Longitudinal Summary ---------------------------------

# First, source the script...
source(here("aux-scripts/longitudinal-summaries.R"))

# ... and now run the function with the respective inputs:
generate_longitudinal_summary(
  .site_name = "Bartlett Hills Golf Course",
  .start_date = "2007-01-01"
)

##------------------------------------------------------------------------------
```

Once you want to run another report, you add it to that file:

```
##------------------------------------------------------------------------------

# Step 1: Update Database ------------------------------------------------------
# Run the follopwing code to update your database.
source(here::here("aux-scripts/update-database.R"))
# Note: Make sure you don't have the file open, or you'll get an error.


# Step 2: Generate Report ------------------------------------------------------
# First, source the file to load the generate_report() function...
source(here::here("aux-scripts/generate-report.R"))

# ... and now run the function with the custom inputs:
generate_report(                            ## current report (just my comment, you don't need to add that)
    .site_name = "Snowmass Club",           ##       |
    .site_name_abbr = "36644-snowmass",     ##       |
    .date_sample_submitted = "2024-09-12",  ##       |
    .start_date = "2007-01-01",             ##       |
    .warm_or_cool = "cool",                 ##       |
    .acid_extract = "Mehlich",              ##       |
    .output = c("pdf", "html")              ##       V
)

generate_report(                            ## previous report (just my comment, you don't need to add that)
    .site_name = "Maroon Creek Club",       ##       |                
    .site_name_abbr = "35873-maroon-creek", ##       |
    .date_sample_submitted = "2024-09-18",  ##       |
    .start_date = "2017-01-01",             ##       |
    .om_seasons = "season",                 ##       |
    .warm_or_cool = "cool",                 ##       |
    .acid_extract = "Mehlich",              ##       |
    .include_results_interpretation = "No", ##       |
    .include_sand_fraction = "Yes",         ##       |
    .output = c("pdf", "html")              ##       V
)


# Optional Step: Generate Longitudinal Summary ---------------------------------

# First, source the script...
source(here("aux-scripts/longitudinal-summaries.R"))

# ... and now run the function with the respective inputs:
generate_longitudinal_summary(
  .site_name = "Bartlett Hills Golf Course",
  .start_date = "2007-01-01"
)

##------------------------------------------------------------------------------
```

To keep it even cleaner, you might want to remove the "longitudinal summary" part in case you don't use it most of the time. If you need it, its usage is explained in the README as well.

Hope this makes sense!
