### ISSUE TITLE
Switched to Main and Getting Error 

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#75]
I just switched to Main branch per your email.  I'm running a test report now.  Got the following error.

  |.......................................................................                      |  77% [sf-results]          Error in `read_data()`:
! Argument 'svg' or 'css' must be a file path, url, or raw vector.
Backtrace:
 1. header_file_create("Physical", "Sand Fraction")
 2. rsvg::rsvg_svg(...)
 3. rsvg:::rsvg_format(...)
 4. rsvg:::read_data(svg)
Called from: signal_abort(cnd)
Browse[1]> 

Quitting from lines 5-7 [unnamed-chunk-183] (./templates/sand_fraction_testing.Rmd)

Quitting from lines 392-399 [sf-results] (report.Rmd)

Here is the report function:

generate_report(
  .site_name = "Maroon Creek Club",
  .site_name_abbr = "35873-maroon-creek",
  .zip_code = 81611,
  .date_sample_submitted = "2024-09-18",
  .start_date = "2017-01-01",
  .om_seasons = "season",
  .warm_or_cool = "cool",
  .acid_extract = "Mehlich",
  .include_results_interpretation = "No",
  .include_sand_fraction = "Yes",
  .output = "html"
)

**Comment by z3tt** [comment]
Ay, it's the logo icons again. Added, now it should work again after you've pulled the latest changes.
