### ISSUE TITLE
R Session Aborted message with new HTML branch

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#8]
I'm getting the following message from R (i.e. it is crashing) on the HTML branch that you just pushed.  I thought it was an issue with my software (R and RStudio) so I uninstalled and reinstalled everything.  It sill did not work.  So just to make sure, I loaded the work-flow branch and tested the Maroon Creek Club generate_report and everything works just fine.  I then went back to the html branch and get the R Session Aborted message.  I'm wondering if it has something to do with fonts?????  I did load the Geographica and Rasa fonts into Font Book on my apple Mac.  It didn't make a difference.  Thoughts????
<img width="1501" alt="Screenshot 2024-05-16 at 3 48 48 PM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/c0703cb7-d34f-495b-8d49-1b08a22b5b40">

**Comment by torv72** [comment]
Figured it out.  I did not have the Geological and Rasa fonts installed properly in Font Book.  I redid it and it works!

**Comment by z3tt** [comment]
Hey Eric, sorry for this experience. It is similar to one of the issues I had back then. Not exactly sure why missing fonts are causing so much trouble, usually it should simply use a fallback font. Maybe it's the geomtextpath package that also relies on the systemfonts package. But just a guess...

Glad it works now!
